import requests
import re
from bs4 import BeautifulSoup
import os.path

__all__ = (
    'get_top100_list',
    'get_song_detail'
)

def custom_make_dir(dirname):
    #프로젝트 컨테이너 폴더 경로
    path_module = os.path.abspath(__file__)
    print(f'path_module: {path_module}')

    root_dir = os.path.dirname(path_module)
    print(f'root_dir: {root_dir}')

    # data/폴더 경로
    path_data_dir = os.path.join(root_dir, dirname)
    print(f'path_data_dir: {path_data_dir}')

    # 만약에 path_data_dir에 해당하는 폴더가 없을 경우 생성해 준다.
    # 실행시 crawler/data폴더가 생성되어야 함.

    os.makedirs(path_data_dir, exist_ok=True)

    return path_data_dir

def get_top100_list(refresh_html=False):
    '''
    실시간 차트 1~100위의 리스트 반환
    :파일위치:
        현재 파일(모듈)의 위치를 사용한 상위 디렉토리 경로(crawler디렉토리):
            os.path.dirname(os.path.abspath(__name__))
        os.path.join()
        data/chart_realtile_100.html
    :param refresh_html: True일 경우, 무조건 새 HTML을 받아와 저장
    :return: 100위 까지의 dict list를 반환
    '''

    path_data_dir = custom_make_dir('data')

    # 1-100위 주소
    url_chart_realtime = 'https://www.melon.com/chart/index.htm'

    # 1~100위에 해당하는 웹페이지 HTML을
    # data/chart_realtime_html에 저장
    source = ''

    file_path = os.path.join(path_data_dir, 'chart_realtime.html')
    try:
        file_mode = 'wt' if refresh_html else 'xt'
        with open(file_path, file_mode) as f:
            response = requests.get(url_chart_realtime)
            source = response.text
            f.write(source)
    except FileExistsError as e:
        print(f'"{file_path}" file is already exists!')
        source = open('melon.html', 'rt').read()

    soup = BeautifulSoup(source, 'lxml')

    result = list()

    for tr in soup.find_all('tr', class_=['lst50','lst100']):
        rank = tr.find('span', class_='rank').text
        title = tr.find('div', class_='rank01').find('a').text
        artist = tr.find('div', class_='rank02').find('a').text
        album = tr.find('div', class_='rank03').find('a').text
        url_img_cover = tr.find('a', class_='image_typeAll').find('img').get('src')
        # .* -> 임의 문자의 최대 반복
        # \. -> '.' 문자
        # .*?. -> '/'이 나오기 전까지의 최소 반복
        p = re.compile(r'(.*\..*?)/')
        url_img_cover = re.search(p, url_img_cover).group(1)
        song_id = tr.find(attrs={'data-song-no':True})['data-song-no']

        result.append({
            'rank': rank,
            'title': title,
            'url_img_cover': url_img_cover,
            'artist': artist,
            'album': album,
            'song_id': song_id
        })
    return result

def get_song_detail(song_list, refresh_html=False):
    '''
    song_id에 해당하는 곡 정보 dict를 반환
    위의 get_top100_list의 각 곡 정보에도 song_id가 들어가도록 추가

    http://www.melon.com/song/detail.htm?songId=30851703
    위 링크를 참조

    파일명
        song_detail_{song_id}.html

    :param song_id: 곡 정보 dict
    :return:
    '''
    path_data_dir = custom_make_dir('song')

    result = list()

    for song in song_list:
        song_id = song['song_id']

        url_song_detail = 'https://www.melon.com/song/detail.htm?songId='+song_id
        filename = 'song_detail_'+song_id+'.html'

        file_path = os.path.join(path_data_dir, filename)
        try:
            file_mode = 'wt' if refresh_html else 'xt'
            with open(file_path, file_mode) as f:
                response = requests.get(url_song_detail)
                source = response.text
                f.write(source)
        except FileExistsError:
            print(f'"{file_path}" file is already exists!')
            source = open(file_path, 'rt').read()

        soup = BeautifulSoup(source, 'lxml')

        title = soup.find('div', class_='song_name')
        artist = soup.find('div', class_='artist')
        if title:
            title = title.text.replace('\t', '').replace('\n', '').replace('\r', '')[2:]
        if artist:
            artist = artist.find('a').find('span').text
        lyrics = soup.find('div', class_='lyric').text
        dic_song_info = dict()
        dic_song_info['title'] = title
        dic_song_info['artist'] = artist
        dic_song_info['lyrics'] = lyrics.replace('\t', '')
        dic_song_info['song_id'] = song_id

        artist_list_prdcr = soup.find('div', class_='section_prdcr')
        if artist_list_prdcr:
            artist_list = artist_list_prdcr.find_all('li')

            for artist in artist_list:
                artist_name = artist.find('div', class_='entry').find('div', class_='artist').find('a').text
                artist_type = artist.find('div', class_='entry').find('div', class_='meta').find('span').text

                dic_song_info[artist_type]=artist_name

        result.append(dic_song_info)
    print("="*50)

    for item in result:
        print(item)

    print(f'result-size: {len(result)}')

    '''
    {'title': '그날처럼', 'artist': '장덕철', 'lyrics': '\n참 많은 시간이 흘러가고넌 어떻게 사는지 참 궁금해날 걱정하는 사람들에게다 잊었단 거짓말하는 내가 참 미운 날아름다운 이별은 세상에 없다지만그때 내가 조금 더 너를 편하게 보내줬다면다른 사람 또 만나 행복할 니가 가끔은내 생각할 때에 지을 표정이 참 궁금해날 보는 네 눈이 좋아서 얼굴 붉히며 딴청 피던 아름답던 그날처럼 좋은 사람 만나 사랑 받고 너도 이젠 웃을 수 있길찬란했던 우리 그날처럼비어있는 지갑에 음식점을 서성이면월급날이라며 손잡아 이끌어주던만 원짜리 커플링 고맙다며 펑펑 울던과분한 네 사랑 받을 사람 참 부러워날 보는 네 눈이 좋아서 얼굴 붉히며 딴청 피던 아름답던 그날처럼 좋은 사람 만나 사랑 받고 너도 이젠 웃을 수 있길찬란했던 우리 그날처럼문득 들려오는 너의 소식에가끔씩은 혼자 울 수 있길끝까지 이기적인 내가이젠 나 없이도 괜찮다 너에게 듣고 싶던 말좋은 사람 만나 미안해 다시 돌아갈 순 없지만아름답던 우리 그날\n', 'song_id': '30755375', '작사': '덕인', '작곡': '장중혁', '편곡': 'Harry'}
{'title': '주인공', 'artist': '선미', 'lyrics': '\n내 몸이 확머리가 휙돌아가 어때지금 기분이우리는 마치자석 같아서로를 안고또 밀쳐내니까너는 날 미치게 하고정신 못 차리게 해그래 알겠지 넌 참날 기가 막히게 해너는 날 춤추게 하고술 없이 취하게 해그래 알겠지 넌 참착한 날 독하게 해우리 둘만의이 영화에진짜 주인공은 너였어 baby그래 넌 오늘도 너답게화려한 주인공처럼그저 하던 대로 해그게 악역이라도나를 슬프게 해도넌 너여야만 해내가 아플지라도슬픈 엔딩이라도the show must go onthe show must go on너는 늘 끝장을 보고모든 걸 덮으려 해왜 날개를 달아주고추락하자 해너는 늘 착하지 라며날 눈물 삼키게 하잖아그래 알겠지 알겠지넌 날 혹하게 해우리 둘만의이 드라마에진짜 주인공은 너였어 baby그래 넌 오늘도 너답게화려한 주인공처럼그저 하던 대로 해그게 악역이라도나를 슬프게 해도넌 너여야만 해내가 아플지라도슬픈 엔딩이라도the show must go onthe show must go on그저 하던 대로 해그게 악역이라도나를 슬프게 해도넌 너여야만 해내가 아플지라도슬픈 엔딩이라도the show must go onthe show must go onyou must go on\n', 'song_id': '30838076', '작사': '선미', '작곡': '24', '편곡': '24'}
{'title': '다른사람을 사랑하고 있어', 'artist': '수지 (SUZY)', 'lyrics': '\n네가 상처받지 않게 어떻게 말을 꺼낼까예쁜 말 적당한 핑계로 널 보내고 난 떠나려 했어일어선 나를 붙잡고 엉엉 울며 매달리기 전 까지 말야 다른 사람을 사랑하고 있어다 말하고 싶지 않았어넌 좋은 사람이니까허물어지는 모래성을 붙잡고더 애를 쓰려 하지 마너 아닌 다른 사람을 사랑하고 있어바란 것도 하나 없이 넌 항상 모든 걸 줬어행복한 내가 너의 행복이라며넌 언제나 나만 바라봤어그런데 너의 사랑이 점점 지쳐변명 하지 않고 다 말할게다른 사람을 사랑하고 있어다 말하고 싶지 않았어넌 좋은 사람이니까허물어지는 모래성을 붙잡고더 애를 쓰려 하지 마너 아닌 다른 사람을 걱정하다가도 까맣게 널 잊을 만큼진심으로 사랑하고 있어아름다웠던 사랑의 끝에서다 말하고 싶지 않았어네가 아플까 봐허물어지는 모래성을 붙잡고더 애를 쓰려 하지 마너 아닌 다른 사람을 사랑하고 있어\n', 'song_id': '30851703', '작사': '아르마딜로', '작곡': '아르마딜로', '편곡': '권영찬'}
{'title': '#첫사랑', 'artist': '볼빨간사춘기', 'lyrics': "\n어릴 때 넌 키도 작고빼빼 말랐지 기억나난 knock 그런 니가괜히 맘에 들어두드려보지만 yeah짓궂게 놀려주는 게나름 나의 맘이었는데Why- Don't you know그런 채로 졸업식But these days너의 소식이 어디서 타고 오는 건지훌쩍 커버린 너는 왜 땜에 멋진 건지내 timeline에 나타나는너의 시간이내 시간을 다 훔쳐가 yeahOh winter night when I meet you나 너를 만나면그 어릴 때 뭐 모를 때사실 널 좋아했다고말해줄 거야 괜히 널 보면못되게 굴었었다고말해줄 거야너도 그 날로 돌아가 솔직 해줄래어릴 때 넌 숫기 없고조용했었지 기억나근데 어쩜 하는 말마다왜 그렇게 예쁘게 하는데이제는 놀릴 수 없이커져버린 너의 어깨가날 설레게 해 따뜻할 것 같아Oh winter night when I meet you나 너를 만나면그 어릴 때 뭐 모를 때사실 널 좋아했다고말해줄 거야 괜히 널 보면못되게 굴었었다고말해줄 거야너도 그 날로 돌아가 솔직 해줄래널 좋아했던 그때가 그리운 걸까아님 지금도 떨리는 걸까yeah너가 걸어오고 있어몸이 얼어붙어 아무 말도 못 하겠어Oh winter night when I meet you흰 눈이 내리면난 아직도 널 보는 게사실 두근거린다고말해줄 거야 이제널 보면 예쁘게 웃어준다고말해줄 거야 너도그 날로 돌아가 솔직 해줄래\n", 'song_id': '30829858', '작사': '김지수', '작곡': '김지수', '편곡': '황종하'}
{'title': '비행운', 'artist': '문문 (MoonMoon)', 'lyrics': '\n매일매일이 잿빛이더라구팽이돌듯이 빙빙 돌더라구어른이 라는 따분한 벌레들이야금야금 꿈을 좀 먹더라구나는 자라 겨우내가 되겠지뿔이 자라난어른이 될테니억지로 라도웃어야지 하는데그럼에도 좀울적하더라구어제와 오늘의 온도가 너무 달라서비행운이 만들어졌네내가 머물기에여기는 너무 높아서한숨자국만 깊게 드러났네나는 자라 겨우내가 되겠지뿔이 자라난어른이 될 테니억지로 라도웃어야지 하는데그럼에도 좀울적 하더라구어제와 오늘의 온도가 너무 달라서비행운이 만들어졌네내가 머물기에여기는 너무 높아서한숨자국만 깊게 드러났네어제와 오늘의 온도가 너무 달라서비행운이 만들어졌네내가 머물기에여기는 너무 높아서한숨자국만 깊게 드러났네꼬마가 간직했던꿈은 무엇일까오래된 일기장을 꺼내봤네1996년 7월 20일에우주 비행사라고 적어놨네\n', 'song_id': '30086173', '작사': '문문 (MoonMoon)', '작곡': '문문 (MoonMoon)', '편곡': '김영철'}
{'title': '답장', 'artist': '김동률', 'lyrics': '\n너무 늦어버려서 미안나 알다시피 좀 많이 느려서몇 번이나 읽어도난 믿어지지 않았나 봐답을 알 수 없던 질문들다음날에 많이 웃겨줘야지난 그랬어지금 생각해 보면 그때넌 안간힘을 쓰고 있었는데널 알아주지 못하고더 실없이 굴던 내 모습얼마나 바보 같았을까내일 맛있는 거 먹자고 혹영화라도 볼까 말하던 내가나 그때로다시 돌아가 네 앞에 선다면하고 싶은 말 너무나 많지만그냥 먼저 널 꼭 안아 보면 안될까잠시만이라도나 그때로다시 돌아갈 기회가 된다면그때보다는 잘할 수 있을까뭔가 그럴듯한 말을 하고 싶은데나 아무래도 내일 쓸까 봐 또 미룰래너무 오래 걸려서 미안지금 보내더라도 어차피달라질 건 없다고넌 이미 모두 잊었다고읽지도 않을 수 있겠지설마 그럴 리가 없다고모른 척했던 시간이 넘 길었어나 그때로다시 돌아가 널 볼 수 있대도어쩌면 나는 그대로일지 몰라사실 아직도 그 답은 잘 모르겠어미안하단 말은 안 할래그렇게 되면 끝나버릴까 봐그러고 나면 똑같아질까 봐혹시 내일이면 알게 될 수 있을까오늘도 미루고 내일도 미루겠지만널 사랑해이것만으론 안 될지 몰라도이제 와서 다 소용없더라도이것밖에 난 하고픈 말이 없는데사랑해 너를\n', 'song_id': '30833270', '작사': '김동률', '작곡': '김동률', '편곡': '정수민'}
{'title': 'instagram', 'artist': 'DEAN', 'lyrics': '\n내일이 올 걸 아는데난 핸드폰을 놓지 못해잠은 올 생각이 없대 yeah다시 인스타그램 인스타그램 하네잘 난 사람 많고 많지누군 어디를 놀러 갔다지좋아요는 안 눌렀어나만 이런 것 같아서저기 인스타그램 인스타그램 속엔문제야 문제온 세상 속에똑같은 사랑노래가와 닿지 못해나의 밤 속엔생각이 너무 많네복잡해틈만 나면 바뀌는 게 관둘래이 놈의 정보화 시대단단히 잘못 됐어요즘은 아는게 더괴로운 것 같은데가면 갈 수록너무 어려워나만 이런 건지클럽 말고 뭐영화 말고 뭐 없나 하다결국 동네내 맘에는 구멍이 있어그건 뭘로도 못 채우는 것 yeah난 지금 가라앉는 중 인걸네모난 바다 속에서문제야 문제온 세상 속에똑같은 사랑 노래가와 닿지 못해나의 밤 속엔생각이 너무 많네뚜루뚜 뚜루뚜all night그렇게 시간 낭비를 하네저 인스타그램 속에서Lonely lonely so lonely원래 이리도 힘든가요no way no way이 피드 속엔나완 다른 세상 뿐인데부질없이올려 놓은 사진뒤에 가려진 내 마음을아는 이 없네난 또 헤 메이네저 인스타그램 속에서그래 너는 요즘 어때잠 못 자는 건 여전해자른 단발이 참 예쁘던데좋아요는 안 눌렀어조금 웃긴것 같아서뚜루루뚜 뚜루루뚜뚜루루뚜all night그렇게 시간 낭비를 하네네 인스타그램 속에서\n', 'song_id': '30806580', '작사': 'Deanfluenza', '작곡': 'highhopes', '편곡': 'highhopes'}
{'title': '선물', 'artist': '멜로망스', 'lyrics': '\n빛이 들어오면 자연스레 뜨던 눈그렇게 너의 눈빛을 보곤사랑에 눈을 떴어항상 알고 있던 것들도 어딘가새롭게 바뀐 것 같아남의 얘기 같던 설레는 일들이내게 일어나고 있어나에게만 준비된 선물 같아자그마한 모든 게 커져만 가항상 평범했던 일상도특별해지는 이 순간별생각 없이 지나치던 것들이이제는 마냥 내겐 예뻐 보이고내 맘을 설레게 해항상 어두웠던 것들도 어딘가빛나고 있는 것 같아남의 얘기 같던 설레는 일들이내게 일어나고 있어나에게만 준비된 선물 같아자그마한 모든 게 커져만 가항상 평범했던 일상도특별해지는 이 순간너를 알게 된 뒤 보이는모든 것들이 너무 예뻐 보여그렇게 신난 아이처럼순수한 사람이 된 것 같아나에게만 준비된 선물 같아자그마한 모든 게 커져만 가항상 평범했던 일상도특별해지는 이 순간깊은 사랑에 빠진 순간\n', 'song_id': '30514366', '작사': '김민석', '작곡': '멜로망스', '편곡': '정동환'}
{'title': 'Havana (Feat. Young Thug)', 'artist': 'Camila Cabello', 'lyrics': "\nHeyHavana ooh na na ayyHalf of my heart is in Havanaooh na na ayy ayyHe took me back to East Atlantana na naAll of my heart is in Havana ayyThere's somethin''bout his manners uh huhHavana ooh na na uhHe didn't walk upwith that how you doin' uhWhen he came in the roomHe said there’s a lot of girlsI can do with uhBut I can't without youI'm doin' foreverin a minute heyThat summer night in JuneAnd papa says he got maloin him uhHe got me feelin' likeOooh oooh oohI knew it when I met himI loved him when I left himGot me feelin' likeOooh oooh oohand then I had to tell himI had to go oh na na na na naHavana ooh na na ayy ayyHalf of my heart is in Havanaooh na na ayy ayyHe took me back to East Atlantana na na uh huhAll of my heart is in Havana ayyMy heart is in Havana ayyHavana ooh na naJefferyJust graduatedfresh on campus mmmFresh out East Atlantawith no manners damnFresh out East AtlantaBump on her bumperlike a traffic jam jamHey I was quick to paythat girl like Uncle Samhere you go ayyBack it on meshawty cravin' on meGet to diggin' on me on meShe waited on me then whatShawty cakin' on megot the bacon on me wait upThis is historyin the makin' on me on mePoint blank close range that beIf it cost a millionthat's me that's meI was gettin' mulaman they feel meHavana ooh na na ayy ayyHalf of my heart is in Havanaooh na na oh ayy ayyHe took me back to East Atlantana na na oh noAll of my heart is in Havana ayyMy heart is in Havana ayyHavana ooh na naOoh na na oh na na na oo oohTake me back back back likeOoh na na oh na na naTake me back back back likeOoh na na oh na na na yea yeahTake me back back back likeOoh na na oh na na naTake me back back backHey heyOooh oooh oohOooh oooh oohTake me back to my HavanaHavana ooh na naHalf of my heart is in Havanaooh na na oh yeahHe took me back to East Atlantana na na ayy ayyAll of my heart is in HavanaMy heart is in Havana ayyHavana ooh na naUh huhOh na na naoh na yeahOh na na naOh na na naNo no no take me backOh na na naHavana ooh na na\n", 'song_id': '30567963'}
{'title': 'Heart Shaker', 'artist': 'TWICE (트와이스)', 'lyrics': "\nYeah Yeah Yeah Yeah YeahCome and be my loveCome and be my love babyYeah Yeah Yeah Yeah YeahCome and be my loveCome and be my love baby멍하니 서서 막 고민고민 해나 이거 진짜 잘하는 짓인지Yeah Yeah Yeah Yeah뭐 어때No No No No미쳤어난 쯔위라고 해 무작정 인사할까내 전화번호야 쪽지를 주고 도망칠까Yeah Yeah Yeah Yeah어떡해No No No No지금이야Girl you can do it눈이 마주치고 있잖아Love is timing놓치면 후회할지 몰라Love is coming coming좀만 더 용기를 내더는 망설이지 마이상하게 생각해도어쩔 수 없어 반했으니까You're my heart shaker shaker놓치기 싫어You're my heart shaker shaker어떡해바보처럼 안 기다려네게 말할래 반해버렸다고네가 맘에 든다고하루 종일 보고 싶다고Would you be my love반해버렸으니까표정관리 해 어색하지 않게말투는 Cool Cool 긴장할 필요 없어Yeah Yeah Yeah Yeah정신 바짝 차리고 집중해No No No No어떡해 똑바로 못 보겠어지금이야Girl you can do it눈이 마주치고 있잖아Love is timing놓치면 후회할지 몰라Love is coming coming좀만 더 용기를 내더는 망설이지 마이상하게 생각해도어쩔 수 없어 반했으니까You're my heart shaker shaker놓치기 싫어You're my heart shaker shaker어떡해바보처럼 안 기다려내가 말할래 반해버렸다고 네가 맘에 든다고하루 종일 보고 싶다고Would you be my love반해버렸으니까너도 날 원하게 될 거야날 사랑하게 될 걸간절히 바라 너도 나와 같기를Oh Yeah망설이지 마 먼저 다가가사랑을 말해 주저 하지 마Come baby be my be mybe my loveCome baby Bae Bae Bae Bae이상하게 생각해도어쩔 수 없어 반했으니까You're my heart shaker shaker놓치기 싫어You're my heart shaker shaker어떡해바보처럼 안 기다려내가 말할래 좋아한다고 네가 맘에 든다고하루 종일 보고 싶다고사랑한다고반해버렸다고You are mine Be mineYou are mine Be mine좋아한다고 말할래반했으니까\n", 'song_id': '30781481', '작사': '별들의 전쟁', '작곡': 'Sean Alexander', '편곡': 'Avenue 52'}
{'title': 'Universe', 'artist': 'EXO', 'lyrics': '\n마음과 반대로 아픈 말이 나와너를 힘들게 했던 나도 내가 힘든 걸다짐과 다르게 나아진 게 없어늘 실망하게 했던 나도 후회하는 걸잊을 수 없을 것 같아바람이 차가워지면입김을 불어서 숨결을 만지던 밤행복한 웃음소리로포근히 끌어안으며별빛처럼 빛날 내일을 꿈꾸던 밤I`ll search the universe널 다시 찾을 때까지놓지 않을 거야 티끌 같은 기억도계절에 새겨진 우리의 추억은 다시몇 번이고 돌아와 널 부를 테니까웃음과 눈물이 상처와 치유가질문과 해답들이 네 안에 다 있는 걸나의 세상을 가진 나의 작은 우주가소멸하는 순간 나도 사라지겠지I`ll search the universe널 다시 찾을 때까지놓지 않을 거야 티끌 같은 기억도계절에 새겨진 우리의 추억은 다시몇 번이고 돌아와 널 부를 테니까기억은 언제나 눈물을 데려와다 씻어낸 자리에 Woo baby너 하나만 남겨 둬단 하루에 단 한번에끊어낼 수 있는 마음이 아니란 걸아프도록 느끼잖아그 어디라고 해도 너에게 가는 나I`ll search the universe널 다시 찾을 때까지놓지 않을 거야 티끌 같은 기억도계절에 새겨진 우리의 추억은 다시기어이 돌아와 널 찾을 테니까그게 사랑이니까사랑이니까\n', 'song_id': '30806536', '작사': '윤사라', '작곡': 'Jeff Lewis', '편곡': 'Mrey'}
{'title': '밤이 되니까', 'artist': '펀치 (Punch)', 'lyrics': '\n오늘도 난 술을 마셔 우울하니까네가 또 생각나니까침대 위에 놓인 전활 꺼 둬야만 해내일 후회할 것 같아서찬 바람이 불어 오면왠지 술 한 잔이 생각나너도 옆에 있으면 좋겠어파도처럼 내게 밀려와나를 어지럽게 만드는네가 오늘따라 더 생각이 나오늘도 난 술을 마셔 밤이 되니까네가 또 생각나니까침대 위에 놓인 전활 꺼 둬야만 해내일 후회할 것 같아서나에게 읽어 주던 시너와 살던 집모든 게 다 생각이 나파란 지붕 밑 강이 보이는 곳한강 위에 비친 달빛이네가 있는 곳을 안다면그곳을 비춰준다면 좋겠어시간은 저녁을 지나 긴 새벽인데왜 자꾸 네가 생각나쓸쓸한 네 빈자리가 날 외롭게 해아직 많이 사랑하나 봐아직은 힘들 것 같아너의 번호를 지운단 건너를 모두 지우는 것 같아서오늘 밤은 너를 찾아가이 말을 전하고 싶어너를 정말 많이 사랑했다고오늘도 난 술을 마셔 비가 오니까네가 또 생각나니까침대 위에 놓인 전활 꺼 둬야만 해내일 후회할 것 같아서이 밤에 술을 한 잔 하는 건모두 그렇지만 나 결국 너를 잊을 걸알면서도 헤어지려는마음이 이렇게 슬프기때문일까 내 탓일까지금은 너도 혹시내 생각 하다 잠 못 들지 않는지너무나 보고 싶어 1분이라도네가 또 보고 싶어보고 싶어\n', 'song_id': '30659630', '작사': '지훈', '작곡': '로코베리', '편곡': '로코베리'}
{'title': 'Roller Coaster', 'artist': '청하', 'lyrics': "\nI remember very first time in love I remember oh oh I remember oh oh 너도 같은 기분일까 so I'm in love I remember oh oh I remember oh 어머 이래도 되는지 싶어 aha 그래 너 때문에 매일 즐거워 조금 서두르는 것 같아도 baby I need your love oh oh I need your love oh oh oh 심장이 훅 내려앉게 달콤해 가끔은 상처받을까 걱정돼 처음부터 모든 걸 알 순 없겠지 하지만 난 다 던져볼래 자꾸 아찔한 이 느낌 위험한 이 느낌 내 손을 꼭 잡아줘 I want you 흔들리지 않게 조금 더 뜨겁게 나를 꼭 더 안아줘 넌 롤러코스터 ooh ahh 롤러코스터 uh woh ahhI need your love ooh ahhbaby your love uh woh ahh빤히 바라볼 때 가슴이 떨려아닌 척 해봐도 뻔히 다 걸려내가 먼저 말하지 않아도이미 다 알아넌 내 맘과 같아 aha너무 빠른 건 아닐까 싶어 aha근데 너 때문에 매일 새로워조금 서툴러도 눈 감아줘 babyI need your love oh ohI need your love oh oh oh시간이 멈춘 것처럼 달콤해갑자기 날 떠날까 봐 걱정돼처음부터 모든 걸 알 순 없겠지하지만 난 다 던져볼래자꾸 아찔한 이 느낌위험한 이 느낌내 손을 꼭 잡아줘 I want you흔들리지 않게 조금 더 뜨겁게나를 꼭 더 안아줘넌 롤러코스터 ooh ahh롤러코스터 uh woh ahhI need your love ooh ahhBaby your love uh woh ahh어쩌다 찾아온 내 사랑I love you I love you모든 게 꿈이 아니기를I love you I love youLook넌 롤러코스터 ooh ahh넌 롤러코스터 baby롤러코스터 uh woh ahh롤러코스터 babyI need your love ooh ahhbaby I need you lovebaby your love uh woh ahh롤러코스터롤러코스터\n", 'song_id': '30844118', '작사': '전군', '작곡': '전군', '편곡': '라도'}
{'title': '기억의 빈자리', 'artist': '나얼', 'lyrics': '\n니가 없는 자리는 투명한 꿈처럼허전한 듯 나를 감싸고무뎌진 마음을꼭 붙잡았던 나는 오늘도 이렇게그대라는 시간은 내 그림자처럼항상 그 자리에낮은 구름같이 무거운하루를 보낸다고차가운 바람이 이 자릴 지나면우리는 사라지나요달아나는 기억의 빈자리를그대는 인정할 수 있나요아직 내 마음엔서로 마주하던 그 눈빛을이어주는 길이 남아있죠돌아선 나날들이 서러운 걸요차가운 바람이 이 자릴 지나면우리는 사라지나요마주치는 기억의 그 자리를 그대는포기할 수 있나요뜨거운 눈물이 이 자릴 지우면영원히 사라지나요무딘 마음이 이 자릴 메우면하루는 살아지나요달아나는 기억의 빈자리를 그대는바라볼 수 있나요미련 가득히 이 자릴 채우면그대는 돌아오나요멀어지는 기억의 그 자리를 나는이젠\n', 'song_id': '30757693', '작사': '나얼', '작곡': '나얼', '편곡': '강화성'}
{'title': 'Lonely (Feat. 태연)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n미안해 내 탓이야 고마워 덕분이야툭하면 내뱉던 네 그 말버릇너도 힘든 걸 난 다 아는데아마 넌 내가 바본 줄 아나 봐우는 얼굴로 나 힘들다 하면정말 나아질까그럼 누가 힘들까 아프다 징징대면모두 다 괜찮아지는데아마 너와 난 착각 속에서로를 가둬둔 지 몰라아냐 너는 날 이해 못 해걱정 어린 네 눈을 볼 때면Baby I’m so Lonely so Lonely나는 혼자 있는 것만 같아요지친 널 볼 때면 내가 너에게혹시 짐이 될까 많이 버거울까Baby I’m so Lonely so Lonely나도 혼자 있는 것만 같아요그래도 너에게 티 내기 싫어나는 혼자 참는 게 더 익숙해날 이해해줘우린 함께 있지만 같이 걷질 않잖아외로움과 괴로움기억 하나 차인 건데넌 왜 자꾸 다르게만적으려 하는 건지Baby I’m so Lonely so Lonely나는 혼자 있는 것만 같아요그래도 너에게 티 내기 싫어나는 혼자 참는 게 더 익숙해날 이해해줘날 내버려 둬Baby I’m so Lonely so Lonely나는 혼자 있는 것만 같아요Baby I’m so Lonely so Lonely나도 혼자 있는 것만 같아요그래도 너에게 숨기기 싫어나는 혼자 참는 게 더 익숙해날 이해해줘\n', 'song_id': '30383758', '작사': '종현 (JONGHYUN)', '작곡': 'IMLAY', '편곡': 'IMLAY'}
{'title': '빛이 나 (Shinin`)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n빛이 빛이 나 너의 눈엔 빛이 빛이 나아주 아주 꽤 아주 아주 아주꽤 아주 꽤아무리 봐도 손발이 말을 안 들어그래 눈도 멀어 가나 봐Oh girl DownOh Come inCome in 해들어와 줘 내 Around에눈 마주친 순간 내 몸이 팔이 다리Body 멈췄어 GirlI’m into you girlNobody nobody더 아늑하게 자릴 만들어 놔Baby 그게 네 위치Oh somebody call me해도 나갈 생각 없어 나의 위치난 네 옆에 붙박이야우린 마치 쌍둥이자리야Oh girl감출 수 없는 걸Baby come inAlways be with youyou you you you youBaby come inAlways be with youyou you you you youBaby come inbe with youyou you you you youBaby come inAlways be with youYeah yeah날 더 꽉 안아줘Yeah yeahWoo woo woo아주 아주 꽤 아주 아주 아주꽤 아주 꽤후광이 비친 새하얀 살결에눈이 멀어 도가까이 갈래 나 몰라 꼭 너밖에 없는 것 같아 지구 위에거닐고 있는 건 오직 너Only you You youOh 날 천천히 더 알아가 줘Oh 널 조금씩 더 내게 보여줘내게 보여줘 Oh baby더 아늑하게 자릴 만들어 놔Baby 그게 네 위치Oh somebody call me해도 나갈 생각 없어 나의 위치난 네 옆에 붙박이야우린 마치 쌍둥이자리야Oh girl감출 수 없는 걸Baby come inAlways be with youyou you you you youBaby come inAlways be with youyou you you you youBaby come inbe with youyou you you you youBaby come inAlways be with youYeah yeah날 더 꽉 안아줘Yeah yeah눈부셔 너의 모든 게네 손에 닿는 모든 게또 하얗게 빛나고 있어 YeahDon’t be shy신기해 널 알아가는 게거침없이 날 더 비춰주고 있어너의 눈이 날 바라볼 때 더 빛이 나아주 아주 꽤 아주 아주 아주꽤 아주 꽤Baby come inAlways be with youyou you you you youBaby come inAlways be with youyou you you you youBaby come inbe with youyou you you you youBaby come inAlways be with youYeah yeah날 더 꽉 안아줘Yeah yeah\n', 'song_id': '30853153', '작사': '종현 (JONGHYUN)', '작곡': '13', '편곡': '13'}
{'title': 'DNA', 'artist': '방탄소년단', 'lyrics': '\n첫눈에 널 알아보게 됐어서롤 불러왔던 것처럼내 혈관 속 DNA가 말해줘내가 찾아 헤매던 너라는 걸우리 만남은 수학의 공식종교의 율법 우주의 섭리내게 주어진 운명의 증거너는 내 꿈의 출처Take it take it너에게 내민 내 손은 정해진 숙명걱정하지 마 love이 모든 건 우연이 아니니까우린 완전 달라 baby운명을 찾아낸 둘이니까우주가 생긴 그 날부터 계속무한의 세기를 넘어서 계속우린 전생에도 아마 다음 생에도영원히 함께니까이 모든 건 우연이 아니니까운명을 찾아낸 둘이니까DNAI want it this love I want it real love난 너에게만 집중해좀 더 세게 날 이끄네태초의 DNA 가 널 원하는데이건 필연이야 I love us우리만이 true lovers그녀를 볼 때마다 소스라치게 놀라신기하게 자꾸만 숨이 멎는 게 참 이상해 설마이런 게 말로만 듣던 사랑이란 감정일까애초부터 내 심장은 널 향해 뛰니까걱정하지 마 love이 모든 건 우연이 아니니까우린 완전 달라 baby운명을 찾아낸 둘이니까우주가 생긴 그 날부터 계속무한의 세기를 넘어서 계속우린 전생에도 아마 다음 생에도영원히 함께니까이 모든 건 우연이 아니니까운명을 찾아낸 둘이니까DNA돌아보지 말아운명을 찾아낸 우리니까후회하지 말아 baby영원히영원히영원히영원히함께니까걱정하지 마 love이 모든 건 우연이 아니니까우린 완전 달라 baby운명을 찾아낸 둘이니까La la la la laLa la la la la우연이 아니니까La la la la laLa la la la la우연이 아니니까DNA \n', 'song_id': '30637982', '작사': 'RM', '작곡': 'RM'}
{'title': '좋니', 'artist': '윤종신', 'lyrics': '\n이제 괜찮니 너무 힘들었잖아우리 그 마무리가 고작 이별뿐인 건데 우린 참 어려웠어잘 지낸다고 전해 들었어 가끔벌써 참 좋은 사람만나 잘 지내고 있어굳이 내게 전하더라잘했어 넌 못 참았을 거야그 허전함을 견뎌 내기엔좋으니 사랑해서 사랑을 시작할 때니가 얼마나 예쁜지 모르지그 모습을 아직도 못 잊어헤어 나오지 못해니 소식 들린 날은 더좋으니 그 사람 솔직히 견디기 버거워니가 조금 더 힘들면 좋겠어진짜 조금 내 십 분의 일 만이라도아프다 행복해 줘억울한가 봐 나만 힘든 것 같아나만 무너진 건가고작 사랑 한번 따위 나만 유난 떠는 건지복잡해 분명 행복 바랬어이렇게 빨리 보고 싶을 줄좋으니 사랑해서 사랑을 시작할 때니가 얼마나 예쁜지 모르지그 모습을 아직도 못 잊어헤어 나오지 못해니 소식 들린 날은 더좋으니 그 사람 솔직히 견디기 버거워너도 조금 더 힘들면 좋겠어진짜 조금 내 십 분의 일 만이라도아프다 행복해 줘혹시 잠시라도 내가 떠오르면걘 잘 지내 물어 봐줘잘 지내라고 답할 걸 모두 다내가 잘 사는 줄 다 아니까 그 알량한 자존심 때문에 너무 잘 사는 척후련한 척 살아가좋아 정말 좋으니딱 잊기 좋은 추억 정도니난 딱 알맞게 사랑하지 못한뒤끝 있는 너의 예전 남자친구일 뿐스쳤던 그저 그런 사랑\n', 'song_id': '30486509', '작사': '윤종신', '작곡': 'Postino', '편곡': 'Postino'}
{'title': '좋아', 'artist': '민서', 'lyrics': '\n이제 괜찮니 너무 힘들었다며 너의 그 마무리가고작 이별뿐일 거라 우린 괜찮다면서잘 지낸다고 전해 들었지? 내겐 정말 참 좋은 사람 만나 잘 지내고 있어 마냥 자상한 사람잘 됐어 우린 힘들었잖아서로 다름을 견뎌 내기엔좋아 사랑해서 사랑을 시작해서 다신 눈물 흘리지 않을 거야 그 기억은 아직도 힘들어 헤어 나오지 못해 니 소식 들린 날은 더좋아 참 그 사람 한없이 날 이해해줘넌 날 몰라도 정말 몰라줬어내 아픔의 단 십 분의 일만이라도 아프다 날 잊어줘억울한가 봐 너만 힘든 것 같니어쩜 넌 그대로니몰래 흘린 눈물 아니 제발 유난 좀 떨지 마간단해 나는 행복 바랬어 그게 언제든 넌 알 바 아닌 걸좋아 사랑해서 사랑을 시작할 때 내가 그렇게 예쁘다면서그 모습을 그가 참 좋아해 너무 날 사랑해줘 아팠던 날 알면서도좋아 참 그 사람 솔직히 너무나 고마워 너도 빨리 행복하면 좋겠어 다음 사람 내 열 배만큼 사랑해줘 다시는 그러지 마혹시 잠시라도 내가 떠오르면 걘 잘 지내 물어봐 줘 잘 지내라고 답할 걸 모두 다  정말 난 정말 잘 살 거니까그 흘렸던 내 눈물 때문에 나를 아낄 거야 후회는 없을 거야좋아 정말 좋아 딱 잊기 좋은 추억 정도야난 딱 알맞게 너를 사랑했어뒤끝 없는 너의 예전 여자 친구일 뿐 길었던 결국 안 될 사랑\n', 'song_id': '30729198', '작사': '윤종신', '작곡': 'Postino', '편곡': '나원주'}
{'title': '겨울소리', 'artist': '박효신', 'lyrics': '\n별이 떨어지는 작은 창밖을 보다 잠들지 못한 밤 나를 달래보다 길었던 가을의 내겐 첫눈 같은 밤 뒤늦은 나만의 겨울이 온 거야 얼룩 하나 남지 않는 별이 가득히 내린 길을 나 혼자 이렇게 걷고 있어 다시 태어난 겨울소리 따라 부르는 깊은 밤 나의 노래가 어디선가 잠든 너를 안아주길 sleep in white 주인도 없는 이 하얀 그림 위에다 그려보고 싶은 너의 이름 하나 아무 말도 없이 하얀 숨 뱉어보다 어느새 멈춘 두 발을 떼어본다 얼룩 하나 남지 않는 별이 가득히 내린 길을 나 혼자 이렇게 걷고 싶어 다시 태어난 겨울소리 따라 부르는 깊은 밤 나의 노래가 어디선가 잠든 너를 안아주기를 sleep in white 온 세상 하얗던 그날의 우리 둘 끝없는 이야기 잠들지 못했던 그날 다시 태어난 겨울소리 따라 부르는 깊은 밤 나의 노래가 어디선가 잠든 너를 안아주길 눈 감으면 나의 품에 네가 있어 sleep in white Ejjel dal lalalszunk(오늘 밤 이 노래와 함께 잠이 들어)edesalmunkhofeher(달콤한 우리의 꿈은 눈처럼 하얗다)Ejjel dal lalalszunk(오늘 밤 이 노래와 함께 잠이 들어)edesalmunkhofeher(달콤한 우리의 꿈은 눈처럼 하얗다)\n', 'song_id': '30810765', '작사': '김이나', '작곡': '박효신', '편곡': '정재일'}
{'title': 'Beautiful', 'artist': 'Wanna One (워너원)', 'lyrics': '\n바보같이 아쉬움 많은 노래가 하늘에 닿기를눈물 속에 밤새운 내 기도가 마음에 닿기를어렸어 내가 이럴 줄은 몰랐어당연한 거라 그땐 생각했었어내게 남겨준 미소가 아직도 이 가슴속에 남아있어솔직히 나 아직은 받는 사랑이 필요한 가봐홀로 남은 시간이 길어질수록 두렵고 그래그때가 그립고 너무 보고 싶고 그래 YeahI miss you so much 이제서야 느껴 우리 공간I miss you so much이렇게 눈물이 나는데 왜 난 몰랐을까So Beautiful Beautiful그 누구 보다 아름다울 너니까아프지 마 울지 마 널 향한 노래가들린다면 다시 돌아와Oh 그리워 그리워거울 속에 혼자 서있는 모습이낯설어 두려워 네가 필요해이제야 느끼는 내가 너무 싫어다시 돌아와기억은 바다처럼 넓은 창고라고그 안에서 하루 종일 헤매도혼자 느끼는 이 외로움마저유일한 너의 흔적이라고억지로 눈 감은 채 견디고 있어 오늘도I miss you so much이제서야 느껴 우리 공간I miss you so much이렇게 눈물이 나는데 왜 난몰랐을까So Beautiful Beautiful그 누구 보다 아름다울 너니까아프지 마 울지 마 널 향한 노래가들린다면 다시 돌아와Oh 그리워 그리워 거울 속에 혼자 서있는 모습이낯설어 두려워 네가 필요해이제야 느끼는 내가 너무 싫어Yeah 이렇게 너처럼 예쁜 꽃을 안고 네 앞에 다시 서고 싶어Yeah 그 시절보다 더 멋진 모습을 하고 네 앞에 나타나고 싶어 Yeah익숙했던 시간들을 손끝으로 그려돌지 않는 시계처럼 제자리서 울어반짝이던 널 천사 같은 널아름다운 널 맘껏 안아보고 싶어꼭 다시 보고 싶어So Beautiful Beautiful어디선가 울고 있진 않을까떠나지마 가지마 사랑한단 거짓말어떤 말이든 좋으니까Oh 그리워 그리워 그리워멀어지던 너의 마지막 그 말 그리워낯설어 두려워 네가 필요해이제야 느끼는 내가 너무 싫어바보같이 아쉬움 많은 노래가 하늘에 닿기를당신 향해 밤새운 내 기도가 마음에 닿기를\n', 'song_id': '30725482', '작사': '키비', '작곡': '우직', '편곡': '우직'}
{'title': 'LIKEY', 'artist': 'TWICE (트와이스)', 'lyrics': '\n설렌다 Me Likey Me Likey LikeyLikey Me Likey Likey Likey두근두근두근 Heart HeartMe Likey Me Likey Likey LikeyMe Likey Likey Likey두근두근두근자꾸 드러내고 싶지자꾸만 사소한 것 하나까지 전부다작은 화면 속에 내가제일 예뻐 보이고파아직은 감춰 이런 내 마음 꾹꾹멋 부린다는 건 정말 귀찮은 거그렇다고 절대 대충할 수가 없는걸매일 가슴 뛰게 해이건 네가 몰라야만 돼그러면서 뻔뻔하게BB크림 파파파 립스틱을 맘맘마카메라에 담아볼까 예쁘게이거 보면 웃어줘 그리고 꼭 눌러줘저 밑에 앙증맞고새빨간 Heart Heart근데 좋아요란 말은 뻔해내 맘 표현하기엔 부족한데근데 좋아요 잠도 못 자도지각하게 돼도 좋은걸설렌다 Me Likey Me Likey LikeyLikey Me Likey Likey Likey두근두근두근 Heart HeartMe Likey Me Likey Likey LikeyMe Likey Likey Likey두근두근두근 Heart Heart숨을 훕 참아 지퍼를 올리게다시 한번 허리를 훕으라차차차 다 입었다 Baby세상엔 예쁜 옷이너무나도 많고 많아BB크림 파파파 립스틱을 맘맘마카메라에 담아볼까 예쁘게이거 보면 웃어줘 그리고 꼭 눌러줘저 밑에 앙증맞고새빨간 Heart Heart근데 좋아요란 말은 뻔해내 맘 표현하기엔 부족한데근데 좋아요 잠도 못 자도지각하게 돼도 좋은걸그저 바라보고 있지아무 말도 할 수 없지조금만 더 다가와요 내 맘 알아줘요더 이상 감추고만 싶지 않아오늘따라 기분이 꿀꿀해안 그런척해 봐도 슬프네 아무 반응 없는 너 땜에 삐졌는데눈치 없이 친구들이나오라고 부르네Oh 잠깐만 잠깐만연락이 이제야 오는걸 Woo하루종일 기분이 왔다 갔다울다가도 다시 신나서 춤추네설렌다 Me Likey Me Likey LikeyLikey Me Likey Likey Likey두근두근두근 Heart HeartMe Likey Me Likey Likey LikeyMe Likey Likey Likey두근두근두근 Heart Heart\n', 'song_id': '30700708', '작사': '전군', '작곡': '전군', '편곡': '라도'}
{'title': 'Ko Ko Bop', 'artist': 'EXO', 'lyrics': "\nShimmie shimmie Ko Ko BopI think I like it긴장은 down down부끄러 말고 어지러운 마음속에 내가 들어가익숙한 듯 부드럽게 네게 번져가Ah woo 고요한 밤이야 Ah woo 널 위한 밤이야참을 수가 없어 빠져가 Yeah yeah 너의 몸짓에 난 취해가 Yeah yeah네가 알던 뻔한 모습의 나를 잊어 오늘숨겨둔 본능이 Shimmie upIt goes down down baby 리듬에 온몸을It goes down down baby 맡기고 소리쳐 Oh 우린 OhWe going Ko Ko BopHeyShimmie shimmie Ko Ko BopI think I like it조금씩 down down수줍어 말고누가 뭐래도 넌 신경 쓰지 말어 지금 이대로아름답기만 해 멈춰버렸음 해 Baby are you downAh woo 마지막 밤이야Ah woo 둘만의 밤이야긴장하지 말고 다가와 Yeah yeah네 모든 걸 내게 맡겨봐 Yeah yeah점점 풀려 가는 고삐 더 내려놔 오늘눈치 보지 말고 Shakin' up It goes down down baby 리듬에 온몸을It goes down down baby 맡기고 소리쳐 Oh 우린 OhBreak it down nowHeyWe go down now Listen밤은 깊어도 더 빛나는 너너의 그 눈빛이 다 내게 말해기분 좋은 밤 넌 원하고 있어알아 It's ok 이제 시작해Let's goIt's about to go goDown down baby 리듬에 온몸을It goes down down baby 맡기고 소리쳐 Oh 우린 OhGoing Ko Ko BopDown down baby 귓가에 속삭여It goes down down baby 내 맘을 불태워 Oh 미쳐 OhGoing Ko Ko Bop\n", 'song_id': '30529996', '작사': '현지원', '작곡': 'MZMC', '편곡': 'Styalz Fuego'}
{'title': 'all of my life', 'artist': '박원', 'lyrics': '\n너무 힘들어 삶에 치이고 되는 것도 없고 가족도 안 보이고 언제부턴가 나도 중요하지 않고없진 않지만 더 많이 가져야사랑도 이어갈 수 있는 이 세상에서all of my lifeyou are all of my life그러고 보면 나 너를 만나 참 많이 변했어 꿈이 생기고 네가 가진 꿈도 이뤄주고 싶었어 나 그러려면더 높은 곳에 올라가야만 했어더 많은 것들을 가져야 가능했어다 가질 때쯤사랑보다 꿈이 더 커졌어all of my life 내가 힘이 들 때you are all of my life 네가 날 채웠는데 다른 어떤 걸로 나를 채워봐도 all of my life you are all of my life 채워지지가 않아 그렇게 우리 바라왔고 간절했던 거잖아이젠 내방에 가득한데 나도 아무것도 없는 방 안에서 넌 혼자이렇게 주저앉아 울고 있었니all of my life 넌 내 전부인데 이 모든 게 다 무슨 소용 있는데 어디선가 이 노랠 듣게 된다면 all of my life all of my life 네 이야기가 맞아 \n', 'song_id': '30550388', '작사': '박원', '작곡': '박원', '편곡': '권영찬'}
{'title': '피카부 (Peek-A-Boo)', 'artist': 'Red Velvet (레드벨벳)', 'lyrics': '\nUhm yeah yah Oh gosh 난리야 Oh gosh 맞아 난 좀 기분파 헤 금방 또 사랑에 빠져 Yeah yeah yeah yeah 새것만 좋아해요 반짝거리죠 다들 그렇잖아요 맞죠 Peek A Boo 설렐 때만 사랑이니까 La la la la la 내 친구 모두 소리쳐 넌 정말 문제야 I’m fine fine fine fine fine fine Peek Peek A Peek A Boo Peek Peek A Peek A Boo 흥이 난 여우 그런 나라구 Peek Peek A Peek A Boo I said 1 2 3 Play the game again 버튼을 눌러보자 쿵푸만큼 빨리 중간에 내 맘 변해도 놀라지 말기 혹시 끌리지 않니 그럼 Excuse me 자 전화해요 밤새 또 놀러 가요 함께 Restart a game 돌진해 롤링해 블랑카 오늘 저녁도 Let’s go 놀이터는 붐비고 지루해질 틈조차 없죠 Yeah yeah yeah 빙글빙글 돌아요 다들 똑같죠 오 마침내 마주친 눈빛 Peek A Boo 새로워요 사랑인가요 La la la la la 내 친구 모두 소리쳐 넌 정말 문제야 I’m fine fine fine fine fine fine Ma Boo Boo Boo Peek A Boo Boo Boo BooPeek Peek A Peek A BooPeek Peek A Peek A BooPeek Peek A Peek A Boo술래는 너로 정해졌어재밌을 거야 끼워 줄게Peek Peek A Peek A Boo저 달이 정글짐에 걸릴시간까지 노는 거야Peek Peek A Peek A BooPeek A Boo 이상해 어라 넌 좀 달라이런 게임 멈추고 너를 다시 보게 돼무섭지 않아 난 새로운 얘기가펼쳐질 거라는 걸 방금 느꼈으니까Peek Peek A Peek A BooPeek Peek A Peek A Boo흥이 난 여우 그런 나라구Peek Peek A Peek A Boo술래는 너로 정해졌어재밌을 거야 끼워 줄게Peek Peek A Peek A Boo저 달이 정글짐에 걸릴시간까지 노는 거야Peek Peek A Peek A Boo술래는 너로 정해졌어재밌을 거야 네가 좋아Peek Peek A Peek A Boo저 달이 정글짐에걸릴 시간이지만 더 놀자Peek Peek A Peek A BooPeek A BooPeek A BooPeek A Boo\n', 'song_id': '30736437', '작사': 'kenzie', '작곡': 'Ellen Berg Tollbom', '편곡': '문샤인'}
{'title': 'Tell Me', 'artist': '인피니트', 'lyrics': '\nAnywhere Anytime어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘도망쳐버렸어 익숙해져 점점착각처럼 끝이 온 줄 알았어다 망쳐버렸어 Eh또 난 뻔한 드라마 속 Eh서 있는 거 같아 텅 비어 허전해그저 후회뿐I luv you in my mind달콤한 너의 말 그때처럼 너에게듣고 싶어 OhI know you in my heart날 위로했던 말돌려볼게 안아볼게다시 뜨거웠던 때로어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘Tell Me LuvLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu luTell me Tell meTell me Tell meLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu lu내게 내게 돌아와 줘 BabeLet’s go I miss you all day너를 그려 매일 마치 화가이 밤이 닳고 닳아꿈속에서도 네가 들려기억을 ReplayDon’t pass me by널 내 품에 줘 Uh널 찾아 헤매 Go walk walk hardI luv you in my mind달콤한 너의 말 그때처럼 너에게듣고 싶어 가고 싶어 지금 네 옆에I know you in my heart날 위로했던 말돌려볼게 안아볼게다시 뜨거웠던 때로어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘Tell Me LuvLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu luTell me Tell meTell me Tell meLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu lu내게 내게 돌아와 줘 Babe듣고 싶어 네 목소리내 귓가를 가득 울린 Melody속삭여줘 다시 한번이렇게나 이기적인 내가널 안아볼게어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘어딜 가든 어디 있든네가 그리워 못 참겠어제발 다시 내게 내게 돌아와 줘제발 다시 내게 내게 돌아와 줘Tell MeLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu luTell me Tell meTell me Tell meLuv luv lu lu lu luLuv luv lu lu lu luLuv luv lu lu lu lu내게 내게 돌아와 줘 Babe\n', 'song_id': '30824600', '작사': 'BLSSD', '작곡': 'BLSSD', '편곡': 'BLSSD'}
{'title': 'Power', 'artist': 'EXO', 'lyrics': '\n머뭇거리지 마 Move on자 시간이 없어너의 미래는 바로 상상에 달렸어두려움 따윈 버려 우린 그래도 돼모든 열쇤 너에게 있는데잠들지 않아도 꿈꾸던 널잊지 않기를 바래 바래오늘 우리 함께신나게 한번 불태워볼까꼭 하나 된 Feeling feelingSo turn me upWe got that power power네가 나를 볼 때서로 같은 마음이 느껴질 때Power power더 강해지는 걸Turn the music up nowWe got that power power이 음악을 통해같이 한목소리로 노래할 때Power power더 강해지는 걸Turn the music up nowPower powerTurn the music up now고민은 이제 그만 Stop시간은 가 지금도 Tik TokWe take a shot떠나자 We got bang bang pow wow이어폰 타고 흘러 나오는 멜로디로시끄러운 소음 덮고볼륨은 Up HighWe got that power everytime잠들지 않아도 꿈꾸던 널잊지 않기를 바래 바래오늘 다시 함께신나게 한번 불태워볼까꼭 하나 된 Feeling feelingSo turn me upWe got that power power네가 나를 볼 때서로 같은 마음이 느껴질 때Power power더 강해지는 걸Turn the music up nowWe got that power power이 음악을 통해같이 한목소리로 노래할 때Power power더 강해지는 걸Turn the music up now지쳐버리는 그날이 오면 기억해 Babe아름다웠던 우릴다시 일어날 수 있는 그 힘은네 안에 있다는 걸We got thatWe got thatWe got thatWe got thatWe got that power power이 음악을 통해같이 한목소리로 노래할 때Power power더 강해지는 걸Turn the music up nowPower powerTurn the music up nowWe got thatWe got that\n', 'song_id': '30616684', '작사': '김혜정', '작곡': 'James Matthew Norton', '편곡': 'LDN Noise'}
{'title': '이 별', 'artist': '길구봉구', 'lyrics': '\n함께였었던 너 지금 어느 별에 있니난 아직도 이별에 있어흩어져가는 하늘에 나를 태워 보면볼 수 있을까 너 있는 곳에혹시 너도 나를 찾고서 있는지마치 시간이 멈춘 듯이너를 기다리고만 있어oh you’re my staroh you’re my star in the sky너의 밤하늘 속에 내가 있다면그 수 많은 별들 중에한 점이라도 채워지면그걸로 좋아 이별이 된대도함께였었던 너 지금 어느 별에 있니난 아직도 이별에 있어환하게 웃어주던니 마지막 모습이 그리워꿈에서 라도 만날까너를 품에 안고 잠들어oh you’re my staroh you’re my star in the sky너의 밤하늘 속에 내가 있다면그 수 많은 별들 중에한 점이라도 채워지면그걸로 좋아 이별이 된대도너를 잊지 않을게oh you’re my staroh you’re my star in the sky너의 밤하늘에도 내가 있다면그 수 많은 별들 중에한 점이라도 채워지면그걸로 좋아 이별이 된대도\n', 'song_id': '30637776', '작사': 'A.Tone', '작곡': '김현석', '편곡': '정찬희'}
{'title': '그리워하다', 'artist': '비투비', 'lyrics': '\nMy life is incompleteIt’s Missing you오늘도 하루를 보내 다를 게 없이하나도 안 어색해 혼자 있는 게너 없인 안될 것 같던 내가 이렇게 살아근데 좀 허전해 난 여전히 거기 있나 봐후련하게 다 털어내 다 다지난 일에 마음 쓰는 게 It’s alright답이 잘 보이는가 싶다가도어느새 날 가두는 감옥이 돼시간은 앞으로만 가는 걸 어째그 동안 난 아무것도 이룬 것이 없네아직도 내 마음속엔 너 Oh oh너를 그리워하다 하루가 다 지났어너를 그리워하다 일 년이 가버렸어난 그냥 그렇게 살아너를 그리워하다 그리워하다다 괜찮을 거라 되뇌어 봐도내 하루에 끝엔 또 너로 남아너 없인 안될 것 같던 내가 이렇게 살아사실 좀 허전해 넌 여전히 여기 있나 봐내 마음은 여전해 아직 너를 원해몇 년이 지나도 난 아직 널 그리워해난 아직 기억해 우리 처음 봤을 때네 옷차림과 머리 스타일도 다 정확하게I pray for you every night and dayI hope that someday soon I can see you once again아직도 내 마음속엔 너 Oh oh너를 그리워하다 하루가 다 지났어너를 그리워하다 일 년이 가버렸어난 그냥 그렇게 살아너를 그리워하다 그리워하다잠에서 깨어 헝클어진 머리처럼 내 일상도꽤나 엉망이 돼버렸어 책임져아무렇지 않은 척 드리워진 표정도 내 모든 곳에스며든 네 흔적도 다 책임져 아직도 난잊을 수 없나 봐 다시 돌아와 줘또다시 같은 엔딩이라 해도 너너를 그리워하다 하루가 다 지났어너를 그리워하다 일 년이 가버렸어너를 잊으려 하다 하루가 지나가도너를 지우려 하다 일 년이 가버려도난 그냥 그렇게 살아너를 그리워하다 그리워하다그리워하다 그리워하다\n', 'song_id': '30672529', '작사': '정일훈', '작곡': '이든 (EDEN)', '편곡': '이든 (EDEN)'}
{'title': '뿜뿜', 'artist': '모모랜드 (MOMOLAND)', 'lyrics': '\n설레어 너와 나의 랑데뷰 랑데뷰내 마음을 들었다 놨다 해 맘대루 맘대루지금 내 눈엔 눈엔 눈엔네 어깨 무릎 발 Oh숨이 탁 막힐 것 같아 난 너만 보면wow wow 정신을 또 놔 놔 네 매력에난 난 놀라게 돼 또 Hit it Hit it Hit it HO우우우 무슨 말이 필요해 넌 숨이 콱 막힐 것 같아 넌 자꾸만 봐 자꾸 와 이제 나만 보게 될 거야 너를 들었다 놓을 거야넌 점점 더 Fall in loveGive it to you My 눈눈눈눈눈눈 눈빛쏟아지는 My 터터터터터터 터치하나뿐인 My 럽럽럽럽럽 My Luver내 머리부터 뿜뿜 내 발끝까지 뿜뿜 뿜뿜 어Just feel it 뿜뿜네 앞에서 난 뿜뿜 네게 줄게 뿜뿜 뿜뿜 어지금 보고 있는 게 꿈은 아닐 걸 Wake Up Wake Up 땡땡이치고 날 만나게 될 걸 Take off Take off매력을 야 뿜어뿜어뿜어뿜어 보여줄게 Pic up the phoneNow or Never Pick up Pick upwow wow 정신없이 쿵 쿵 내 마음을 뿜 뿜 사정없이 또 Hit it Hit it Hit it HO우우우 여기서 뭘 어떻게 더낮이나 밤이나 빛이나 미쳤나봐떨리지 막 떨려와 이제 나만 생각 날 거야 밤에 잠도 잘 못 잘 거야 점점 더 Fall in loveGive it to you My 눈눈눈눈눈눈 눈빛쏟아지는 My 터터터터터터 터치하나뿐인 My 럽럽럽럽럽 My Luver내 머리부터 뿜뿜 내 발끝까지 뿜뿜 뿜뿜 어우 너만 보면 너만 보면 내 가슴이 뿜뿜뿜뿜뿜뿜뿜뿜 뿜우 자꾸 봐도 자꾸 봐도 내 가슴이 쿵쿵쿵쿵뿜뿜뿜뿜Give it to you My 눈눈눈눈눈눈 눈빛쏟아지는 My 터터터터터터 터치하나뿐인 My 럽럽럽럽럽 My Luver내 머리부터 뿜뿜 내 발끝까지 뿜뿜 뿜뿜 어Just feel it 뿜뿜네 앞에서 난 뿜뿜 네게 줄게 뿜뿜 뿜뿜 어\n', 'song_id': '30816860', '작사': '낭이', '작곡': '낭이', '편곡': '신사동 호랭이'}
{'title': '봄날', 'artist': '방탄소년단', 'lyrics': "\n보고 싶다이렇게 말하니까 더 보고 싶다너희 사진을 보고 있어도보고 싶다너무 야속한 시간나는 우리가 밉다이젠 얼굴 한번 보는 것 조차힘들어진 우리가여긴 온통 겨울 뿐이야8월에도 겨울이 와마음은 시간을 달려가네홀로 남은 설국열차니 손 잡고 지구 반대편까지 가겨울을 끝내고파그리움들이 얼마나눈처럼 내려야 그 봄날이 올까Friend허공을 떠도는작은 먼지처럼 작은 먼지처럼날리는 눈이 나라면조금 더 빨리네게 닿을 수 있을 텐데눈꽃이 떨어져요또 조금씩 멀어져요보고 싶다 보고 싶다보고 싶다 보고 싶다얼마나 기다려야또 몇 밤을 더 새워야널 보게 될까 널 보게 될까만나게 될까 만나게 될까추운 겨울 끝을 지나다시 봄날이 올 때까지꽃 피울 때까지그곳에 좀 더 머물러줘 머물러줘니가 변한 건지니가 변한 건지아니면 내가 변한 건지내가 변한 건지이 순간 흐르는 시간조차 미워우리가 변한 거지 뭐모두가 그런 거지 뭐그래 밉다 니가 넌 떠났지만단 하루도 너를잊은 적이 없었지 난솔직히 보고 싶은데이만 너를 지울게그게 널 원망하기보단덜 아프니까시린 널 불어내 본다연기처럼 하얀 연기처럼말로는 지운다 해도사실 난 아직 널 보내지 못하는데눈꽃이 떨어져요또 조금씩 멀어져요보고 싶다 보고 싶다보고 싶다 보고 싶다얼마나 기다려야또 몇 밤을 더 새워야널 보게 될까 널 보게 될까만나게 될까 만나게 될까You know it allYou're my best friend아침은 다시 올 거야어떤 어둠도 어떤 계절도영원할 순 없으니까벚꽃이 피나봐요이 겨울도 끝이 나요보고 싶다 보고 싶다 보고 싶다 보고 싶다조금만 기다리면며칠 밤만 더 새우면만나러 갈게 만나러 갈게데리러 갈게 데리러 갈게추운 겨울 끝을 지나다시 봄날이 올 때까지꽃 피울 때까지그곳에 좀 더 머물러줘 머물러줘\n", 'song_id': '30244931', '작사': 'SUGA', '작곡': 'SUGA'}
{'title': '그때의 나, 그때의 우리', 'artist': '어반자카파', 'lyrics': '\n그때의 나 그때의 우리참 어리석고 어렸지그때의 우리 아무것도 아닌 일에다투던 초라할 무렵에 기억달 밝은 날에 하늘을 보면우리 상처들이 떠 있고밤 또 늦은 밤에 거릴 거닐면그때의 추억이 선명하게 따라와네가 그립거나 보고프거나그런 쉬운 감정이 아니야난 그때의 우리가 세상에우리밖에 없었던 그때가 그리울 뿐그때의 우리 소홀함과 편안함그 안에서 부서질 듯 아파했던 달 밝은 날에 하늘을 보면우리 상처들이 떠 있고밤 또 늦은 밤에 거릴 거닐면그때의 추억이 선명하게 따라와네가 그립거나 보고프거나그런 쉬운 감정이 아니야난 그때의 우리가 세상에우리밖에 없었던 그때가 그리워다시 그 시간으로 돌아가고픈가벼운 순간의 감정이 아냐난 그때의 우리가 너와 내가이 세상 전부였던 그때가 그리울 뿐그때의 나 그때의 우리\n', 'song_id': '30709103', '작사': '박용인 (어반 자카파)', '작곡': '박주희', '편곡': 'Mad House'}
{'title': '지나갈 테니 (Been Through)', 'artist': 'EXO', 'lyrics': '\n익숙하겠지 또다시감기처럼 툭 걸린밀려드는 잿빛에수없이 지나쳐도 여전히참아내야 해지나갈 테니 지나갈 테니잠깐이면 돼지나갈 테니 지나갈 테니지나갈 테니 이미회색 빛 하늘 위엔분명히 더 밝은 빛이먹구름 걷힌 뒤엔눈부시게 빛날 테니You shine like the starsYou light up my heart오늘의 시련 끝엔찬란하게 나를 비춰Dadada Dadada DumDadada Dadada Dum정신 차리고다시 일어나 툴툴 털고더 이상 나에겐 고통은스쳐가는 소나기모두 참아내야 해지나갈 테니 지나갈 테니잠깐이면 돼지나갈 테니 지나갈 테니지나갈 테니 이미회색 빛 하늘 위엔분명히 더 밝은 빛이먹구름 걷힌 뒤엔눈부시게 빛날 테니You shine like the starsYou light up my heart오늘의 시련 끝엔찬란하게 나를 비춰이게 끝은 아니겠지더 짙은 날도 있겠지그날의 끝에도 너는이렇게 비춰주겠지눈부신 빛을 가린 먹구름 뒤 해변함없이 넌 나를 비추네 영원해고요한 공기 따뜻한 바람도 함께거기 그대로 있어 항상 같은 자리에Yeah회색 빛 하늘 위엔분명히 더 밝은 빛이먹구름 걷힌 뒤엔눈부시게 빛날 테니You shine like the starsYou light up my heart오늘의 시련 끝엔찬란하게 나를 비춰찬란하게 나를 비춰\n', 'song_id': '30806539', '작사': 'JQ', '작곡': 'Heavy', '편곡': 'Rice n` Peas'}
{'title': 'Stay', 'artist': 'EXO', 'lyrics': "\nHey 흩어진 온기이별 위로 나를 밀어낸 파도부서진 우릴 담아바다에 띄워 더 멀리Hey 너의 빈 공간시간은 까맣게 굳어져 그만시선을 돌려 왜 넌내게는 아파 그게 더Can't believe can't believe사랑이 멎었단 너의 말 모두 부서진 우리의 추억너의 잔해 속을 다시 걸어가 난Can't believe can't believe이렇게 멈춰 선 너를 난영원을 그린 우리는 어디결국 끝내 내가 하지 못한 말 StayHey 어긋난 우리검은 수면 위로 비치는 너의 이름그 속에 더 깊이 빠질수록환영처럼 너는 멀어져 가Hey 내 흔적 위로넌 다시 밀려와선 모든 걸 지워나쁜 꿈이라 말해내게 넌 비극 길고 긴Can't believe can't believe사랑이 멎었단 너의 말 모두 부서진 우리의 추억너의 잔해 속을 다시 걸어가 난Can't believe can't believe이렇게 멈춰 선 너를 난영원을 그린 우리는 어디결국 끝내 내가 하지 못한 말 Stay난 믿을 수가 없어 믿지 않아 Yeah다 지울 수가 없어 지우지 않아 Yeah작은 단 한 조각도 잊지 말자라는 말을 지키란 말지키려고 나는 아직 여기 있잖아 BabyHow you do that to me Baby how you do that to meI can't believe this 우리 추억은 Killing me softly난 미끄러져 이별 위로 너와 찢어지고내게 남아있는 두 가지는 이별 위로 다 내 잘못이지 널 붙잡거나 남아 있어 달란 말도 못했으니Woo baby now how we doing정말 남이 됐지 우리 둘이 Woo yeah 전부 사라졌지 But I can't believeCan't believe can't believe언젠간 괜찮아진단 말내게는 이미 더 깊이 스민결국 끝내 내가 하지 못한 말 StayStay Stay내 곁에\n", 'song_id': '30806540', '작사': 'Sik-K (식케이)', '작곡': 'Terence Lam', '편곡': 'Terence Lam'}
{'title': '썸 탈꺼야', 'artist': '볼빨간사춘기', 'lyrics': '\n표현이 서툰 것도 잘못인가요 나 차가운 도시에 따뜻한 여잔데그냥 좋아한단 말도 안 되는가요 솔직하게 난 말하고 싶어요사라져 아니 사라지지 마 네 맘을 보여줘 아니 보여주지 마하루 종일 머릿속에 네 미소만 우리 그냥 한번 만나볼래요나 오늘부터 너랑 썸을 한번 타볼 거야 나 매일매일 네게 전화도 할 거야밀가루 못 먹는 나를 달래서라도 너랑 맛있는 걸 먹으러 다닐 거야넘넘 스윗한 넌 정말 달콤한 걸넘넘 스윗한 넌그냥 좋아한단 말도 안 되는가요 솔직하게 난 말하고 싶어요사라져 아니 사라지지 마 네 맘을 보여줘 아니 보여주지 마하루 종일 머릿속에 네 미소만 우리 그냥 한번 만나볼래요나 오늘부터 너랑 썸을 한번 타볼 거야 나 매일매일 네게 전화도 할 거야밀가루 못 먹는 나를 달래서라도 너랑 맛있는 걸 먹으러 다닐 거야사랑은 이렇게 생기는 게 아니겠어 어쩌면 내 맘의 반쪽을 네게 걸어보는 건데나는 오늘도 네게 차일 것만 같아도 난 한번 더 너에게 다시 달려가 볼 거야나 오늘부터 너랑 썸을 한번 타볼 거야 나 매일매일 네게 전화도 할 거야매운 거 못 먹는 나를 달래서라도 너랑 맛있는 걸 먹으러 다닐 거야나도 그 애처럼 좋아요 좀 눌러줘 나도 너랑 말 좀 할 수 있게 해줘나는 풀이 죽어서 오늘도 포기하고 뒤를 돌아볼 때쯤 나를 붙잡는 넌넘넘 스윗한 넌 정말 달콤한 걸넘넘 스윗한 넌\n', 'song_id': '30657307', '작사': '안지영', '작곡': '바닐라맨 (바닐라어쿠스틱)', '편곡': '바닐라맨 (바닐라어쿠스틱)'}
{'title': '밤편지', 'artist': '아이유', 'lyrics': '\n이 밤 그날의 반딧불을당신의 창 가까이 보낼게요음 사랑한다는 말이에요나 우리의 첫 입맞춤을 떠올려그럼 언제든 눈을 감고음 가장 먼 곳으로 가요난 파도가 머물던모래 위에 적힌 글씨처럼그대가 멀리 사라져 버릴 것 같아늘 그리워 그리워여기 내 마음속에모든 말을 다 꺼내어 줄 순 없지만사랑한다는 말이에요어떻게 나에게그대란 행운이 온 걸까지금 우리 함께 있다면 아얼마나 좋을까요난 파도가 머물던모래 위에 적힌 글씨처럼그대가 멀리 사라져 버릴 것 같아또 그리워 더 그리워나의 일기장 안에모든 말을 다 꺼내어 줄 순 없지만사랑한다는 말이 밤 그날의 반딧불을 당신의창 가까이 띄울게요음 좋은 꿈 이길 바라요\n', 'song_id': '30314784', '작사': '아이유', '작곡': '김희원', '편곡': '김희원'}
{'title': 'Fall', 'artist': 'EXO', 'lyrics': "\n시간도 잠시 길을 잃었던 곳하늘한 몸짓에 그만 매료된 채로걷잡을 수 없이 네가 내 안에 번져너로만 가득히 담은 시야숨조차 쉴 수 없는 걸 It's not easy baby벗어나려 할수록 깊어져그냥 이대로 Fall fall fall for you너의 늪으로 Fall fall 빠져가 끝없이잠길 듯 차오르는 숨이오히려 편안해 더 깊게Fall fall빠져가엉킨 시선에 날 매듭지은 채 넌 무의식까지 침범하려 해위험하단 걸 알면서 한 걸음 더 난 다가서 숨조차 쉴 수 없는 걸 It's not easy baby헤어나려 할수록 짙어져그냥 이대로 Fall fall fall for you너의 늪으로 Fall fall 빠져가 끝없이잠길 듯 차오르는 숨이 오히려 편안해 더 깊게Fall fall 난 네게빠져가희미하게 비친 하늘에나를 그려줘 더 짙게 그려줘 더 날오랫동안 너의 기억에 너의 기억에 Baby나를 새겨줘 더 깊게 새겨줘 더 깊게Yeah 거짓말은 써 알면서 거짓말을 써빠진 거라 했지만 사실 날 빠트린 넌 깊어 끝이 없이 보여 스며들어 조여잃어버려 다 되돌릴 순 없어천천히 들이켜 의미 없는 숨 말해줘 지금 널 해가 깨기 전 보내줘 영원히 나의 품으로잠길 것 같아 숨 쉴 때마다 그냥 이대로 Fall fall fall for you너의 품으로 Fall fall 빠져가 끝없이꺼질 듯 아득해진 느낌 이 순간 난 너만 허락돼Fall fall 난 네게빠져가\n", 'song_id': '30806541', '작사': 'MQ', '작곡': 'MZMC', '편곡': 'Rice n` Peas'}
{'title': 'Good Night', 'artist': 'EXO', 'lyrics': "\n이렇게 너처럼 아름다운 밤이 내리면잠든 세상에 난 포근히 안겨서 좋은 꿈을 꾸겠지저 멀리 하늘 위에 작은 별이우리가 걸어가는 길을 비추고너의 귓가에다 내가 간직했던사랑을 속삭여주던 그날Baby good night꿈속에 그려보던 순간에 난 그대로 멈춰버리고만 싶어다시 널 내 품에 안기를 원해아직네가 그리워 난 어디서도 너를 찾을 수 없어 넌 없는데아름다운 이 밤은 돌아오고아무것도 남지 않은 빈자리는 커져자꾸만참 이상한 일이야널 만날 수 없는데 여전히 널나의 시간도 나의 계절도아무 일 없이 흘러 Yeah난 이렇게 너처럼 아름다운 밤이 내리면잠든 세상에 눈을 감고 난 조용히 안겨서 너의 꿈을 꾸겠지유난히 반짝이던 너의 눈빛너무나 부드러운 너의 목소리너의 손길을 다시 한 번만느껴볼 수만 있다면 YeahOoh 습관처럼 난Ooh 너를 생각하게 되는 걸Ooh 밤을 비춰주던 별이 자꾸 흐려져 너와 나의 거리처럼 자꾸만 멀어져아침이 오면 너를 잊어버린 채 나에게로 또다시 이 밤이 오기만 기다려I won't give up baby I'll be waiting for you네가 없는 아름다운 밤이또다시 나를 찾아와가만히 눈을 감아 난널 떠올리다나도 모르게 잠이 들어\n", 'song_id': '30806543', '작사': 'JQ', '작곡': 'MZMC', '편곡': 'Rice n` Peas'}
{'title': '비밀정원', 'artist': '오마이걸', 'lyrics': '\n나의 비밀정원난 아직도 긴 꿈을 꾸고 있어 그 어떤 이에게도 말하지 못했던 아침 햇살이 날 두드리며 hello 매일 머물렀다 가는데 모르지 처음으로 너에게만 보여줄게 나를 따라 come with me bae 손을 잡아 you and me 내 안에 소중한 혼자만의 장소가 있어 아직은 별거 아닌 풍경이지만 조금만 기다리면 곧 만나게 될 걸 이 안에 멋지고 놀라운 걸 심어뒀는데 아직은 아무것도 안 보이지만 조금만 기다리면 알게 될 거야 나의 비밀정원 너무 단순해 그 사람들은 말야 눈으로 보는 것만 믿으려 하는 걸 빗방울은 날 다독이며 잠시 내게 또 힘을 주곤 해 다정히 오늘 하루 한 사람만 초대할게 나를 따라 come with me bae 상상해봐 you and me 내 안에 소중한 혼자만의 장소가 있어 아직은 별거 아닌 풍경이지만 조금만 기다리면 곧 만나게 될 걸 이 안에 멋지고 놀라운 걸 심어뒀는데 아직은 아무것도 안 보이지만 조금만 기다리면 알게 될 거야 나의 비밀정원 아마 언젠가 말야 이 꿈들이 현실이 되면 함께 나눈 순간들을 이 가능성들을 꼭 다시 기억해줘 네 안에 열렸던 문틈으로 본 적이 있어 아직은 별거 아닌 풍경이지만 조금만 기다리면 곧 만나게 될 걸 그 안에 멋지고 놀라운 걸 심어뒀는데 아직은 아무것도 안 보이지만 조금만 기다리면 알게 될 거야 너의 비밀정원 무럭무럭 어서어서 자라나 줘 beautiful\n', 'song_id': '30827192', '작사': '서지음', '작곡': 'Sean Alexander', '편곡': 'Steven Lee'}
{'title': 'Lights Out', 'artist': 'EXO', 'lyrics': '\n숨 쉬는 것조차힘겨울 만큼눈물이 차오를 땐가끔씩내 안에 숨어 울어도 괜찮아그래도 돼지나갈 테니까내 품에 잠이 들어이대로 깨지는 마요다시 또 아침이 올 테니외로움 끝에선 그대가편히 꿈 꿀 수 있도록오늘은 그만 불을 꺼줘고개를 들었을 땐미소를 띠어줘아픔 따윈 잊도록소중했던작은 추억들 모두 간직한 채잠이 들 수 있게이젠 혼자가 아닌 걸더 이상 외롭진 마요이대로 아침이 올 테니슬픔의 끝에선 그대가편히 웃을 수 있도록오늘은 그만 불을 꺼줘하늘이 구름에 가려지듯그대도 잠시 가려진다면 다시 또그댈 그댈그댈 비춰줄게내 품에 잠이 들어이대로 깨지는 마요다시 또 아침이 올 테니외로움 끝에선 그대가편히 꿈 꿀 수 있도록오늘은 그만 불을 꺼줘\n', 'song_id': '30806544', '작사': '첸 (CHEN)', '작곡': 'Jason `Arner` Housman', '편곡': 'Jason `Arner` Housman'}
{'title': '시차 (We Are) (Feat. 로꼬 & GRAY)', 'artist': '우원재', 'lyrics': "\n밤새 모니터에 튀긴 침이마르기도 전에 강의실로아 참 교수님이 문신 땜에 긴 팔 입고 오래난 시작도 전에 눈을 감았지날 한심하게 볼 게 뻔하니 이게 더 편해내 새벽은 원래 일몰이 지나고하늘이 까매진 후에야 해가 뜨네내가 처량하다고 다 그래야 야 난 쟤들이 돈 주고 가는파리의 시간을 사는 중 이라 전해난 이게 궁금해시계는 둥근데 날카로운 초침이 내 시간들을 아프게모두가 바쁘게뭐를 하든 경쟁하라 배웠으니우린 우리의 시차로 도망칠 수밖에이미 저 문밖엔 모두 그래야 일찍 일어나야 성공해 안 그래맞는 말이지 다근데 니들이 꿈을 꾸던 그 시간에나도 꿈을 꿨지두 눈 똑바로 뜬 채로We're livin' in a different time zone바뀌어버린 낮과 밤이야 yeahHave a good night 먼저 자아직 난 일하는 중이야We are who we areWe a-a-are who we a-a-are ohahhDon't you know who we are4호선 문이 열릴 때취해 있는 사람들과 날 똑같이 보지마그들이 휘청거릴 때마다풍기는 술 냄새마저 부러웠지만난 적응해야 했거든 이 시차꿈을 꾸게 해 준 침댄 이 기차먼지 쌓일 틈이 없던 키보드 위그리고 2009년부터 지금까지 계속GRAY on the beat ya아침은 까맣고 우리의 밤은 하얘난 계속 칠하고 있고 똑같은 기찰 타네걱정한 적 없어 막차 시간은 한 번도얇았던 커튼이 햇빛을 완벽히 못 가려도난 지금 눈을 감아야 해내일의 나는 달라져야 해우린 아무것도 없이 여길 올라왔고넌 이 밤을 꼭 기억해야 돼We're livin' in a different time zone바뀌어버린 낮과 밤이야 yeahHave a good night 먼저 자아직 난 일하는 중이야We are who we areWe a-a-are who we a-a-are ohahhDon't you know who we are밤새 모니터에 튀긴 침이마르기도 전에 대기실로아 참 문신 땜에 긴 팔 입고 오래녹화 전에 눈을 감고 생각하지똑같은 행동 다른 느낌시차 부적응에 해당돼지금 내 옆엔 Loco 그리고 GRAY모두 비웃었던 동방의 소음이 어느새전국을 울려대야 이게 우리 시차의 결과고우린 아직 여기 산다 전해We're livin' in a different time zone바뀌어버린 낮과 밤이야 yeahHave a good night 먼저 자아직 난 일하는 중이야We are who we areWe a-a-are who we a-a-are ohahhDon't you know who we are모두 위험하다는 시간이 우린 되려 편해Don't you know who we are밝아진 창문 밖을 봐야지 비로소 맘이 편해Don't you know who we are모두가 다 피하는 반 지하가 우린 편해Don't you know who we areWe are We are We areDon't you know who we are\n", 'song_id': '30613202', '작사': 'GRAY (그레이)', '작곡': 'GRAY (그레이)', '편곡': 'GRAY (그레이)'}
{'title': '눈 (Feat. 이문세)', 'artist': 'Zion.T', 'lyrics': '\n내일 아침 하얀 눈이 쌓여 있었으면 해요그럼 따뜻한 차를 한 잔 내려드릴게요계속 내 옆에만 있어 주면 돼요약속해요눈이 올까요우리 자는 동안에눈이 올까요그대 감은 눈 위에눈이 올까요아침 커튼을 열면 눈이 올까요서두르지 마요 못다 한 얘기가 있어요잠이 들고 나면 오늘은 어제가 되어버려요계속 내 곁에만 있어 주면 돼요약속했죠눈이 올까요우리 자는 동안에눈이 올까요그대 감은 눈 위에눈이 올까요아침 커튼을 열면 눈이 올까요잘 봐요 밖이 유난히 하얗네요눈 눈이 와요눈 눈이 와요눈이 와요눈이 와요창 밖에도 눈이 와요어제 우리 말한 대로차를 한 잔 내려드릴게요\n', 'song_id': '30753021', '작사': 'Zion.T', '작곡': '윤석철', '편곡': '윤석철'}
{'title': '환상통 (Only One You Need)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n눈을 뜰 때마다 더 또렷해감히 넌 상상도 못하던 것목표 못 삼을 절대적인 것You’re always right and I’m wrong스치듯 마주친 손끝엔아직 두려운 불안함이가득한 걸 알아 나는그것도 너니까 이해해 Oh두 눈 또렷한 이유귓불 밑이 뜨거워진 이유손끝 저릿한 기분널 감당할 건 나뿐이야아무도 못해Only One You NeedNeed needOnly One You NeedNeed needThe Only One You NeedNeed need널 만족시켜 주려 해Right hereI just gotta blow Oh너와 난 사라졌던 그 한 조각I wanna be the only oneThe Only One You Need눈부시게 아름다운 건 항상 그래쓰러질 듯 또 흔들려곧 터질 듯 위태롭게 빛나늘 불안할수록 더욱더온몸 찢어져 흩어져도내가 다 감싸 안을 테니여기 안겨 널 터트려뭐든 괜찮아 널 안았으니 Yeah두 눈 또렷한 이유귓불 밑이 뜨거워진 이유손끝 저릿한 기분널 감당할 건 나뿐이야아무도 못해Only One You NeedNeed needOnly One You NeedNeed need너와 난 사라졌던 그 한 조각I wanna be the only oneThe Only One You NeedI can’t wait for you흐트러진 폼이위험해 보여 YeahYeah 긴장은 풀어내게 다 맡겨줘나와 같은 널 보고만 있을 순 없어I wanna beI wanna be the only oneThe Only One You Need Yeah너와 난 사라졌던 그 한 조각I wanna beI wanna be the only oneThe Only One You NeedOnly One You NeedNeed needThe Only One You Need사라졌던 그 한 조각I wanna be theOnly One You Need\n', 'song_id': '30853154', '작사': '종현 (JONGHYUN)', '작곡': 'MZMC', '편곡': 'G.Bliz & Blasian Chris'}
{'title': '바보야', 'artist': '허각', 'lyrics': '\n기억 속에 또 조용히 찾아와너무 사랑한 기억 아련히 떠올라서가까이 조금만 한걸음 조금만 다가가니까그 자리에 내가 갈 때까지만딴 데 눈 돌리지 마 아픈 그대나는 바보야 이런 너를 떠나보내놓고나는 바보야 후회하는 거밖에 몰라서정말 너무 아프다 가슴 치면서 울고 있잖아이젠 내게 와줘 바보야맘에 없는 말인 줄 알면서 너도 바보야내 맘 알잖아 이젠 내게 와줘 바보야내겐 너뿐이야잊고 살 수가 없는 그대라서가슴속에 묻은 채 여전히 떠올라서혼자 살아갈 수도 없게 아직 날 괴롭히네나는 바보야 이런 너를 떠나보내놓고나는 바보야 후회하는 거밖에 몰라서정말 너무 아프다 가슴 치면서 울고 있잖아이젠 내게 와줘 바보야맘에 없는 말인 줄 알면서 너도 바보야내 맘 알잖아 이젠 내게 와줘 바보야내겐 너뿐이야천천히 조금만 한 걸음씩 조금만내 가슴은 널 향하고 있잖아너도 바보야 이런 나를 떠나보내놓고너도 바보야 후회하는 거밖에 몰라서정말 너무 아프다 가슴 치면서 울고 있잖아제발 돌아와 줘 바보야아직 사랑하는 걸 알면서 나도 바보야내 맘 알잖아 이젠 내게 와줘 바보야내겐 너뿐이야\n', 'song_id': '30753213', '작사': '박강일', '작곡': '박강일', '편곡': '박강일'}
{'title': '잘 해보려는 나 알 수 없는 너', 'artist': '윤딴딴', 'lyrics': '\n내가 너를 좋아한진 좀 됐어하루 종일 온통니 얼굴이 떠나지 않아늦은 밤에 니 생각에못 자는 날이 많아졌어진정이 안 돼내가 너를 미워한 지도 좀 됐어하루 종일 내가 연락하는 것마다무심해 보여솔직히 그리부담 주지도 않은 것 같은데 넌 왜내가 좋다 하면너도 좋다 하고내가 만나자면만나자 하고또 내가 보고 싶다면너도 보고 싶다면서 왜 꼭결정적일 때는좋다 해도시큰둥하고내가 만나 재도답장이 없어작은 캔커피 들고너의 집 앞에서또 기다리다돌아가네 난사실 난 니가 참 어려워알다가도 모를 것 같아솔직히 그리소심하지도 않은 성격인데난 왜내가 좋다 하면너도 좋다 하고내가 만나자면만나자 하고또 내가 보고 싶다면너도 보고 싶다면서 왜 꼭결정적일 때는좋다 해도시큰둥하고내가 만나 재도답장이 없어작은 캔커피 들고너의 집 앞에서또 기다리다돌아가네 넌 참사람 초라하게 만드네니가 좋다 하면나도 좋다 했고니가 만나자면바로 달려갔고또 니가 웃어 준다면뭐든 할 것 같은 난데 왜 넌더 다가가려 하면좋다 해도시큰둥하고내가 만나 재도답장이 없어작은 꽃다발 들고너의 집 앞에서또 기다리는어떻게든 잘 해보려는 나도무지 알 수 없는 너\n', 'song_id': '30855650', '작사': '윤딴딴', '작곡': '윤딴딴', '편곡': '임진강'}
{'title': '에너제틱 (Energetic)', 'artist': 'Wanna One (워너원)', 'lyrics': "\n너와 나의 입술이 점점 느껴지는 이 순간 속에 뜨거운 공기 온몸에 전율이 와 이제 너와 내가 써 내릴 Story I don't know why 나도 모르게 더 빠져들어가 숨 막히게 Baby I don't know why 지금 이 순간 멈출 수 없는 기분 No No No No Make me feel so high 미치겠어 날 멈출 순 없어 You make me feel so high I'm so crazy 너가 나를 본 순간 막 끌려 더 날 당겨줘 Baby I'm feelin’ so energetic 오늘 밤 둘이 Out of control Yeah I'm feelin’ so energetic 내 심장이 멈추는 그 순간까지 너를 지켜줄게 사라지지 않게 한 순간의 작은 약속들은 아냐 이젠 말해 내게 Baby You tell me how to feel Uh 1 2 3 & 4 니 옆의 딴 놈들이 거슬려 좀 Who am I 오직 너만을 지키는 킬러 말 그대로 난 좀 죽여줘 Yeah Uh 너를 품에 안고 비상해 걱정은 버려 지하에 뭐를 하든 간에 하나라는 수식어가 맴돌 거야 너와 나의 귓가에 Make me feel so high 미치겠어 날 멈출 순 없어 You make me feel so high I'm so crazy 너가 나를 본 순간 막 끌려 더 날 당겨줘 Baby I'm feelin’ so energetic 오늘 밤 둘이 Out of control Yeah I'm feelin’ so energetic I'm feelin’ good I wanna touch 멈출 수 없는 이 기분은 마치 Freedom I'm feelin’ good I wanna touch baby 어서 내게 와줘 Tonight Yeah Alright Oh Oh Work your body 다가와서 즐길 시간이 Let’s dance 아껴둔 너의 신발이 더러워지더라도 움직여 빨리 Hurry up 질문은 나중에 해딴 남자들은 넘보지 말게누가 봐도 So 쿨하게이제 시작해 You know I mean막 끌려 더 날 당겨줘 BabyI'm feelin’ so energetic너와 단둘이 Out of control YeahI'm feelin’ so energetic\n", 'song_id': '30568338', '작사': '우석', '작곡': '후이', '편곡': 'Flow Blow'}
{'title': '가시나', 'artist': '선미', 'lyrics': "\n너의 싸늘해진 그 눈빛이나를 죽이는 거야 커지던 니 맘의 불씨재만 남은 거야 왜시간이 약인가 봐 어째 갈수록 나 약하잖아슬픈 아픔도 함께 무뎌지는 거야좋아 이젠 너를 잊을 수 있게 꽃같이 살래 나답게Can't nobody stop me now no try me 나의 향길 원해 모두가 바보처럼 왜 너만 몰라정말 미친 거 아냐 넌왜 예쁜 날 두고 가시나날 두고 가시나왜 예쁜 날 두고 가시나날 두고 떠나가시나그리 쉽게 떠나가시나같이 가자고 약속해놓고 가시나 가시나 날카로운 날 보고 넌고개 숙일 거야 가시 난 내 모습이더 깊숙이 파고들 거야 eh이미 꺾은 거잖아 굳이 미안해하지 마정말 꺾인 건 지금 내가아냐 바로 너야좋아 이젠 너를 잊을 수 있게꽃같이 살래 나답게Can't nobody stop me now no try me 나의 향길 원해 모두가 바보처럼 왜 너만 몰라정말 미친 거 아냐 넌왜 예쁜 날 두고 가시나날 두고 가시나왜 예쁜 날 두고 가시나날 두고 떠나가시나그리 쉽게 떠나가시나같이 가자고약속 해놓고가시나 가시나 너는 졌고 나는 폈어And it's over 다시 돌아온다 해도 지금 당장은 나 없이 매일 잘 살 수 있을 것 같지암만 생각해봐도 미친 거 아냐 넌왜 예쁜 날 두고 가시나날 두고 가시나왜 예쁜 날 두고 가시나날 두고 떠나가시나그리 쉽게 떠나가시나같이 가자고 약속해놓고 가시나 가시나\n", 'song_id': '30587846', '작사': '24', '작곡': 'Joe Rhee', '편곡': 'Joe Rhee'}
{'title': '가을 안부', 'artist': '먼데이 키즈', 'lyrics': '\n어떠니 잘 지냈니 지난 여름유난히도 힘에 겹더라 올핸새벽녘엔 제법 쌀쌀한 바람이 어느덧니가 좋아하던 그 가을이 와사랑도 그러게 별수없나 봐언제 그랬냐는 듯 계절처럼 변해가그리워져 미치도록 사랑한 그날들이내 잃어버린 날들이참 많이 웃고 울었던 그때그 시절의 우리니가 떠올라 밤새참 아프다 니가 너무 아프다너를 닮은 이 시린 가을이 오면보고 싶어서 너를 안고 싶어서가슴이 너를 앓는다어떠니 넌 괜찮니 지금쯤은나를 잊고 편안해졌니 이젠우습지 잘살길 바라면서도막상 날 잊었을 널 떠올리면 서글퍼그리워져 미치도록 사랑한 그날들이내 잃어버린 날들이참 많이 웃고 울었던 그때그 시절의 우리니가 떠올라 밤새참 아프다 니가 너무 아프다너를 닮은 이 시린 가을이 오면보고 싶어서 너를 안고 싶어서가슴이 너를 앓는다너라는 계절 안에 살아여전히 너를 꿈꾸며고마워져 그 날들이내 지나버린 날들이추억은 짐이 아니라살게 하는 힘이란 걸가르쳐준 너니까또 설렌다 아프도록 설렌다너를 닮은 눈부신 가을이 오면니가 떠올라 그리움이 차올라눈물로 너를 앓는다밤새 또 너를 앓는다\n', 'song_id': '30669593', '작사': '강은경', '작곡': '이도형', '편곡': '이도형'}
{'title': '연애소설 (Feat. 아이유)', 'artist': '에픽하이 (EPIK HIGH)', 'lyrics': '\n우리 한때 자석 같았다는 건한쪽만 등을 돌리면 멀어진다는 거였네.가진 게 없던 내게네가 준 상처 덕분에나도 주인공이 돼보네in a sad love story.별 볼 일 없던 내게네가 준 이별 덕분에나도 주인공이 돼보네in a sad love story.In this sad love story.잊을 때도 됐는데기억에 살만 붙어서 미련만 커지네.되돌아보면가슴을 찢어지게 하는데하필 전부 명장면이네.기억나?캄캄한 영화관.너와 내 두 손이 처음 포개졌던 날.감사했어.한평생 무수한 걸 짓고 무너뜨렸을 네 손이내 손에 정착한 것을.기억나?네가 가족사를 들려준 밤.그건 나만 아는 너 한 조각 주고픈 마음.비가 와 이불 밑에서넌 내 몸을 지붕 삼아 이 세상의 모든 비를 피했어.다 기억나, 네가 없는 첫 아침도.잘 참다 끝내 무너진 그 순간을.한참 울었거든 샤워실에서,비누에 붙은 너의 머리카락을 떼며.가진 게 없던 내게네가 준 상처 덕분에나도 주인공이 돼보네in a sad love story.별 볼 일 없던 내게네가 준 이별 덕분에나도 주인공이 돼보네in a sad love story.In this sad love...가랑비 같은 슬픔이라 위로했지만여전히 젖은 얼굴로 잠에서 깨.계절은 무심코 변하고 앞만 보는데난 서성이네 여태시간도 버리고 간 기억뿐인 네 옆에.잊지 못해. 술기운에 이끌려 마주했었던 둘의 첫날밤.사실 술 한잔 부딪히기도 전에 취했지.우리가 마신 건 운명인 것 같아.너무나 빠르게도 깨어난 우리.한때는 죽고 못 살 것만 같던 날들이전쟁 같은 매일이 돼.죽일 듯 서로를 바라보며 맞이하게 된 눈물의 끝.필연이라 믿던 첫 만남부터악연이라며 돌아선 마지막까지도우린 서로 마주 보는 거울이었지.서로가 던진 눈빛에 깨질 때까지도.가진 게 없던 내게네가 준 상처 덕분에나도 주인공이 돼보네in a sad love story.별 볼 일 없던 내게네가 준 이별 덕분에나도 한소절 가져보네in a sad love story.In this sad love...나에게만 특별한 얘기.참 진부하죠?나만 이런 게 아닌 건 알지만내가 이런 걸.줄 게 없었던 내게남겨준 상처 덕분에나도 누군가에게 주네나 닮은 sad story.다 처음이었던 내게네가 준 두려움 덕분에난 영원히in a sad love story.In this sad love story.우리 한때 자석 같았다는 건한쪽만 등을 돌리면 멀어진다는 거였네.우리 한때 자석 같았다는 건한쪽만 등을 돌리면 남이 된다는 거였네.서울 하늘엔 별 하나 없네.\n', 'song_id': '30688500', '작사': '미쓰라 진', '작곡': 'DJ 투컷츠', '편곡': 'DJ 투컷츠'}
{'title': 'Shape of You', 'artist': 'Ed Sheeran', 'lyrics': "\nThe club isn’t the best place to find a lover So the bar is where I go Me and my friends at the table doing shots drinking fast and then we talk slow you come over and start up a conversation with just me and trust me I’ll give it a chance now Take my hand stop put van the man on the jukebox and then we start to dance And now I’m singing like Girl you know I want your love Your love was handmade for somebody like me Come on now follow my lead I may be crazy don’t mind me Say boy let’s not talk too much Grab on my waist and put that body on me Come on now follow my lead Come come on now follow my lead I’m in love with the shape of you We push and pull like a magnet do Although my heart is falling too I’m in love with your body Last night you were in my room And now my bed sheets smell like you Every day discovering something brand new I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Every day discovering something brand new I’m in love with the shape of you One week in we let the story begin We’re going out on our first date You and me are thrifty So go all you can eat Fill up your bag and I fill up a plate We talk for hours and hours about the sweet and the sour And how your family’s doing ok leave and get in a taxi then kiss in the backseat Tell the driver make the radio play and I'm singing like Girl you know I want your love Your love was handmade for somebody like me Come on now follow my lead I may be crazy don’t mind me Say boy let’s not talk too much Grab on my waist and put that body on me Come on now follow my lead Come come on now follow my lead I’m in love with the shape of you We push and pull like a magnet do Although my heart is falling too I’m in love with your body Last night you were in my room And now my bed sheets smell like you Every day discovering something brand new Well I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Oh I Oh I Oh I Oh I I’m in love with your body Every day discovering something brand new I’m in love with the shape of you Come on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onI’m in love with the shape of youWe push and pull like a magnet doAlthough my heart is falling tooI’m in love with your bodyLast night you were in my roomAnd now my bed sheetssmell like youEvery day discoveringsomething brand newWell I’m in love with your bodyCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onCome on be my baby come onEvery day discoveringsomething brand newI’m in love with the shape of you\n", 'song_id': '30188113'}
{'title': 'BABY IT`S U (PROD. 키겐, earattack)', 'artist': '정세운', 'lyrics': "\nBeautiful Girl두 눈가에 두 눈가에 네가 젖어 들어조심스레 조심스레널 품 안에 넣어 yeah끌어안어 yeah혹시 깨질까 봐 손을 놓칠까 봐난 흔들려두 귓가에 두 귓가에네가 크게 울려조심스레 조심스레가슴에 퍼져 yeah내 맘을 적셔 yeah나만 알고 싶어 너라는 멜로디너 말곤 아무 의미 없어시시해 표현 못한 게 너무 많아재촉해 재촉해 눈부신 미소가득히 웃어준Baby it’s U Baby it’s U내 모든 것을 걸어네 마음을 다 열어더 반짝반짝 거리게Baby it’s UGirl you knowthat you're my only oneBaby it’s UMake me wanna stayin'all night long너를 꼭 닮은 별빛 아래서나 영원이라는 꿈을 꿔볼래 마침내Baby it’s U은하수 넘어 네게 걸어가는이 공간 속에 ooh수많은 별들이 속삭여My beautiful sunshineYou are the bright lightin this universe yeah새하얀 눈처럼 내 안에소복이 계절이 지나도 날 불러재촉해 재촉해 그토록오랫동안 기다려준Baby it’s U Baby it’s U내 모든 것을 걸어네 마음을 다 열어더 반짝반짝 거리게Baby it’s UGirl you knowthat you're my only oneBaby it’s UMake me wanna stayin'all night long너를 꼭 닮은 별빛 아래서나 영원이라는 꿈을 꿔볼래 마침내Baby it’s Uooh ooh ooh eh ohU ooh ooh ooh eh oh그래 너 하나로 난 꿈을 꿔아무것도 난 안 두려워세상이 너를 널 중심으로 돌아가네Baby it’s U Baby it’s U매일 같은 길을 걸어우린 이별 따윈 없어더 반짝반짝 빛날게Baby it’s UGirl you knowthat you're my only oneBaby it’s UMake me wanna stayin'all night long너를 꼭 닮은 별빛 아래서나 영원이라는 꿈을 꿔볼래 마침내Baby it’s U\n", 'song_id': '30857381', '작사': 'earattack', '작곡': '키겐', '편곡': '키겐'}
{'title': '고민보다 Go', 'artist': '방탄소년단', 'lyrics': "\nDOLLAR DOLLAR하루아침에 전부 탕진달려 달려 내가 벌어 내가 사치달려 달려 달려 달려달려 달려난 원해 cruisin' on the bay원해 cruisin' like NEMO돈은 없지만 떠나고 싶어 멀리로난 돈은 없지만 서도풀고 싶어 피로돈 없지만 먹고 싶어 오노 지로열일 해서 번 나의 pay전부 다 내 배에티끌 모아 티끌 탕진잼 다 지불해내버려둬 과소비 해버려도내일 아침 내가 미친놈처럼내 적금을 깨버려도WOO 내일은 없어내 미랜 벌써 저당 잡혔어WOO 내 돈을 더 써친구들 wussupDo you want someDOLLAR DOLLAR하루아침에 전부 탕진달려 달려man i spend it like some partyDOLLAR DOLLAR쥐구멍 볕들 때까지해가 뜰 때까지YOLO YOLO YOLO YOYOLO YOLO YO탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOWhere my money yah탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOYOLO YOLO YO탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOWhere the party yah탕진잼 탕진잼 탕진잼Where my money yahWhere the party yah내 일주일 월화수목 금금금금내 통장은 yah밑 빠진 독이야난 매일같이 물 붓는 중차라리 걍 깨버려걱정만 하기엔 우린 꽤 젊어오늘만은 고민보단 Go해버려쫄면서 아끼다간 똥이 돼버려문대버려DOLLAR DOLLAR하루아침에 전부 탕진달려 달려man i spend it like some partyDOLLAR DOLLAR쥐구멍 볕들 때까지해가 뜰 때까지YOLO YOLO YOLO YOYOLO YOLO YO탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOWhere my money yah탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOYOLO YOLO YO탕진잼 탕진잼 탕진잼YOLO YOLO YOLO YOWhere the party yah탕진잼 탕진잼 탕진잼고민보다 Go고민보다 Go고민보다 Go GoEverybody고민보다 Go고민보다 Go고민보다 Go GoEverybody고민보다 Go고민보다 Go고민보다 Go GoEverybody고민보다 Go고민보다 Go고민보다 Go GoEverybody고민보다 Go고민보다 Go고민보다 Go GoEverybody고민보다 Go고민보다 Go고민보다 Go GoEverybody\n", 'song_id': '30637988', '작사': 'Supreme Boi', '작곡': 'Supreme Boi'}
{'title': '첫눈처럼 너에게 가겠다', 'artist': '에일리', 'lyrics': '\n널 품기 전 알지 못했다내 머문 세상 이토록 찬란한 것을작은 숨결로 닿은 사람겁 없이 나를 불러준 사랑몹시도 좋았다너를 지켜보고 설레고우습게 질투도 했던평범한 모든 순간들이캄캄한 영원그 오랜 기다림 속으로햇살처럼 니가 내렸다널 놓기 전 알지 못했다내 머문 세상 이토록 쓸쓸한 것을고운 꽃이 피고 진 이 곳다시는 없을 너라는 계절욕심이 생겼다너와 함께 살고 늙어가주름진 손을 맞잡고내 삶은 따뜻했었다고단 한번 축복그 짧은 마주침이 지나빗물처럼 너는 울었다한번쯤은 행복하고 싶었던 바람너까지 울게 만들었을까모두 잊고 살아가라내가 널 찾을 테니니 숨결 다시 나를 부를 때잊지 않겠다너를 지켜보고 설레고우습게 질투도 했던니가 준 모든 순간들을언젠가 만날우리 가장 행복할 그날첫눈처럼 내가 가겠다너에게 내가 가겠다\n', 'song_id': '30190630', '작사': '이미나', '작곡': '로코베리', '편곡': '로코베리'}
{'title': '그 사람을 아나요', 'artist': '임창정', 'lyrics': '\n내가 사랑했던그 사람을 알고 있나요여기 곁에 있던그때 멈춰버린많이 사랑 받던 시간들다시 살아야 하는데계속 따라가도 더 멀어진 그대다시 올까 오늘도 이렇게그토록 원망했었던그토록 미워했었던 나를날 다시 한 번 안아줄 수 있나요그대 떠밀려가던 날그 마지막까지 날 걱정했었나요그땐 보내줘야내가 행복할 줄 알았나요정말 사랑했던그 사람을 알고 있나요여기 곁에 있던 oh내겐 멈춰버린많이 사랑 받던 시간들살아야 하는데 oh다시 떠올려도 더 멀어진 기억잊혀질까 오늘도 이렇게그토록 원망했었던그토록 미워했었던 나를날 다시 한 번 안아줄 수 있나요그대 떠밀려가던 날그 마지막까지 날 걱정했었나요그땐 보내줘야내가 행복할 줄 알았나요그 가슴에 있던매일매일 나를 기다리던그대와 똑같이 아파서 울어요 나그토록 원망했었던그토록 미워했었던 나를이 눈물을 위로 해줄 수 있나요그대 떠밀려가던 날그 마지막까지 날 걱정했었나요그땐 보내줘야내가 행복할 줄 알았나요\n', 'song_id': '30688990', '작사': '임창정', '작곡': '멧돼지', '편곡': '멧돼지'}
{'title': '노력', 'artist': '박원', 'lyrics': '\n널 만날 수 있는 날 친굴 만났고끊이지 않던 대화가 이젠 끊기고널 바라보다가 다른 사람을 겹쳐봤어누군가 내 안에 들어온 것도 아닌데사랑한단 말은 점점 미안하고억지로 한 것뿐인데 넌 좋아하고너에게만 나는 아주 바쁜 사람내 연락을 기다리다가 또 잠들겠지나도 노력해봤어 우리의 이 사랑을안되는 꿈을 붙잡고 애쓰는 사람처럼사랑을 노력한다는 게 말이 되니서로가 다른 건 특별하다고같은 건 운명이라 했던 것들이 지겨워져넌 오늘보다 내일 날 더 사랑한대난 내일보다 오늘 더 사랑할 텐데나도 노력해봤어 우리의 이 사랑을아픈 몸을 이끌고 할 일을 끝낼 그때처럼사랑을 노력한다는 게 말이 되니말이 되니사랑을 노력한다는 게 노력으로 안되는 게 있다는 게사랑을 노력한다는 게 말이 되니 너는 아직 아무것도 모르고만 있는데어떻게 말해야 할지 나도 모르겠어그렇게 널 만나러 가\n', 'song_id': '30099927', '작사': '박원', '작곡': '박원', '편곡': '권영찬'}
{'title': '우린 봄이 오기 전에 (Before Our Spring)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n우린 봄이 오기 전에 따뜻하기 전에 한번 볼까요우린 날이 밝기 전에 모두 잠들었을 때 꼭 만나요사실은 난 널 바라보는 게 지켜보는 게 좋아가만히 웃는 널 바라보는 게 그냥 지켜보는 게 편해바보 같은 말이지만네 앞에 나서는 게 두려워 네가 날 이해 못한대도괜찮아 괜찮아 아직 봄이 오기까지는 꽤나 남아 있으니까사실은 난 또 봄이 오는 게 따뜻해지는 게 싫어가만히 웃는 널 멀리서 보기만 해도 가슴이 아리는데바보 같은 말이지만네 앞에 나서는 게 두려워 네가 날 이해 못한대도괜찮아 괜찮아 아직 봄이 오기까지는 꽤나 남아 있으니까이번 봄은 예전보다 빨리 온다지요차갑게 얼은 겨울은 아직 그대로인데어찌해야 하나 고민 말아요난 괜찮아요 또 내게도 봄이 오겠죠난 네 앞에 나서는 게 두려워 혹시 너에게 옮길까 봐내 눈물 내 슬픔 잊고 내게도 봄이 오면 그땐 그땐 그땐그땐\n', 'song_id': '30853163', '작사': '종현 (JONGHYUN)', '작곡': '위프리키', '편곡': '위프리키'}
{'title': '한숨', 'artist': '이하이', 'lyrics': '\n숨을 크게 쉬어봐요 당신의 가슴 양쪽이 저리게 조금은 아파올 때까지 숨을 더 뱉어봐요 당신의 안에 남은 게 없다고  느껴질 때까지  숨이 벅차올라도 괜찮아요 아무도 그댈 탓하진 않아 가끔은 실수해도 돼 누구든 그랬으니까  괜찮다는 말  말뿐인 위로지만누군가의 한숨 그 무거운 숨을 내가 어떻게헤아릴 수가 있을까요당신의 한숨그 깊일 이해할 순 없겠지만괜찮아요 내가 안아줄게요숨이 벅차올라도 괜찮아요아무도 그댈 탓하진 않아가끔은 실수해도 돼누구든 그랬으니까 괜찮다는 말말뿐인 위로지만누군가의 한숨그 무거운 숨을내가 어떻게헤아릴 수가 있을까요당신의 한숨그 깊일 이해할 순 없겠지만괜찮아요내가 안아줄게요남들 눈엔 힘 빠지는한숨으로 보일진 몰라도나는 알고 있죠작은 한숨 내뱉기도 어려운하루를 보냈단 걸이제 다른 생각은 마요깊이 숨을 쉬어봐요그대로 내뱉어요누군가의 한숨그 무거운 숨을내가 어떻게헤아릴 수가 있을까요당신의 한숨그 깊일 이해할 순 없겠지만괜찮아요내가 안아줄게요정말 수고했어요\n', 'song_id': '8086947', '작사': '종현 (JONGHYUN)', '작곡': '위프리키', '편곡': 'Philtre'}
{'title': 'MIC Drop', 'artist': '방탄소년단', 'lyrics': "\nYeah 누가 내 수저 더럽대I don’t care 마이크 잡음금수저 여럿 패버럭해 잘 못 익은 것들스테끼 여러 개거듭해서 씹어줄게 스타의 저녁에World Business 핵심섭외 1순위 매진많지 않지 이 class 가칠 만끽좋은 향기에 악췬 반칙Mic mic bungeeMic mic bungeeBright light 전진망할 거 같았겠지만 I'm fine sorry미안해 Billboard미안해 worldwide아들이 넘 잘나가서 미안해 엄마대신해줘 니가 못한 효도우리 콘서트 절대 없어 포도I do it I do it 넌 맛없는 라따뚜이혹 배가 아프다면 고소해Sue itDid you see my bagDid you see my bag트로피들로 백이 가득해How you think bout thatHow you think bout thatHater들은 벌써 학을 떼이미 황금빛 황금빛 나의 성공I'm so firin' firin' 성화봉송너는 황급히 황급히 도망 숑숑How you dareHow you dareHow you dare내 손에 트로피 아 너무 많아너무 heavy 내 두 손이 모잘라MIC DropMIC Drop발 발 조심너네 말 말 조심Lodi dodi 아 너무 바빠너무 busy 내 온몸이 모잘라MIC DropMIC Drop발 발 조심너네 말 말 조심이거 완전 네 글자사필귀정 ahOnce upon a time이솝우화 fly니 현실을 봐라 쌔 쌤통지금 죽어도 난 개행복이번엔 어느 나라 가비행기 몇 시간을 타Yeah I'm on the mountainYeah I'm on the bay무대에서 탈진MIC Drop baamDid you see my bagDid you see my bag트로피들로 백이 가득해How you think bout thatHow you think bout thatHater들은 벌써 학을 떼이미 황금빛 황금빛 나의 성공I'm so firin' firin' 성화봉송너는 황급히 황급히 도망 숑숑How you dareHow you dareHow you dare내 손에 트로피 아 너무 많아너무 heavy 내 두 손이 모잘라MIC DropMIC Drop발 발 조심너네 말 말 조심Lodi dodi 아 너무 바빠너무 busy 내 온몸이 모잘라MIC DropMIC Drop발 발 조심너네 말 말 조심Haters gon' hatePlayers gon' playLive a life manGood luck더 볼 일 없어 마지막 인사야할 말도 없어 사과도 하지 마더 볼 일 없어 마지막 인사야할 말도 없어 사과도 하지 마잘 봐 넌 그 꼴 나지우린 탁 쏴 마치 콜라지너의 각막 깜짝 놀라지꽤 꽤 폼나지 포 포 폼나지\n", 'song_id': '30637987', '작사': 'RM', '작곡': 'RM'}
{'title': '비도 오고 그래서 (Feat. 신용재)', 'artist': '헤이즈 (Heize)', 'lyrics': '\n비도 오고 그래서  네 생각이 났어 생각이 나서 그래서  그랬던거지 별 의미 없지 오늘은 오랜만에 네 생각을 하는 날이야 일부러 난 너와 내가 담겨 있는 노랠 찾아 오늘은 슬프거나 우울해도 괜찮은 맘이야 어차피 이 밤이다 지나가면은 별 수도 없이난 또 한 동안은 널 잊고 살테니까내 가슴 속에만품고 살아갈테니까비도 오고 그래서네 생각이 났어생각이 나서 그래서그랬던거지별 의미 없지우산 속에 숨어서네 집을 지나쳐그 날의 감정을다시 느껴보고파서떨어지는 빗물과시계 초침 소리가방 안 가득 채우면그 때로 난 돌아가차라리 난 이 비가그치지 않았음 해매일 기억 속에 살 수 있게나 널 아프게 했던못난 놈이니까널 다시 품에 안을자격도 없으니까비도 오고 그래서네 생각이 났어생각이 나서 그래서그랬던거지별 의미 없지우산 속에 숨어서네 집을 지나쳐그 날의 감정을다시 느껴보고파서우리에게 주어진 행복을너무 빨리 쓴 것 같아거기까지 인 것 같아이 비가 그칠 땐 각자 있던 곳에서다시 살아가야만 해비도 오고 그래서네 생각이 났어생각이 나서 그래서그랬던거지별 의미 없지우산 속에 숨어서네 집을 지나쳐그 날의 감정을다시 느껴보고파서\n', 'song_id': '30492279', '작사': '헤이즈 (Heize)', '작곡': '다비 (DAVII)', '편곡': '다비 (DAVII)'}
{'title': 'There`s Nothing Holdin` Me Back', 'artist': 'Shawn Mendes', 'lyrics': "\nI wanna follow where she goesI think about her and she knows itI wanna let her take control'Cause everytime that she gets close yeahShe pulls me in enough to keep me guessingAnd maybe I should stop and start confessingConfessing yeahOh I've been shakingI love it when you go crazyYou take all my inhibitionsBaby there's nothing holding me backYou take me places that tear up my reputationManipulate my decisionsBaby there's nothing holding me backThere's nothing holding me backThere's nothing holding me backShe says that she is never afraidJust picture everybody nakedShe really doesn't like to waitNot really into hesitationPulls me in enough to keep me guessingAnd maybe I should stop and start confessingConfessingOh I've been shakingI love it when you go crazyYou take all my inhibitionsBaby there's nothing holding me backYou take me places that tear up my reputationManipulate my decisionsBaby there's nothing holding me backThere's nothing holding me back'Cause if we lost our minds and we took it way too farI know we'd be alright I know we would be alrightIf you are by my side and we stumbled in the darkI know we'd be alright I know we would be alright'Cause if we lost our minds and we took it way too farI know we'd be alright I know we would be alrightIf you are by my side and we stumbled in the darkI know we'd be alright we would be alrightOh I've been shakingI love it when you go crazyYou take all my inhibitionsBaby there's nothing holding me backYou take me places that tear up my reputationManipulate my decisionsBaby there's nothing holding me backThere's nothing holding me backI feel so free when you're with me babyBaby there's nothing holding me back\n", 'song_id': '30380953'}
{'title': '와플 (#Hashtag)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n와플 먹어십자가 네 개 붙어있어 맹신해Yes #Hashtag이름에 붙여서침대에 늘어져 보는 거Search search박혀 있어 방구석에서 늘어져 있어쟤랑 걔 사귄대 난 별로 관심 없는데난리 났어가만히 있어도물어뜯을 걸 갖다 줘 고맙지 뭐걸레짝 되면 또 딴 얘깃거리갈아타면 되지 뭐심심했는데 잘 됐어그래서 어떻게 됐다고와플 먹어 너도 한번 씹어 악플 먹어쟤랑 걔랑 사귄대그렇다 카더라내 친구의 사촌의선배의 친구의 사돈이 봤대그렇다 카더라쟤랑 걔랑 싸웠대그렇다 카더라다 뒤집고 엎고 치고아수라 난장판 내놨대아니면 말고도가 텄어 다들 도가 텄어남 얘기하는 거걔가 성격이그리 거지 같대 그래 보여아니 별건 없고 그냥 태도가 별로야눈빛이나 주머니 손꼽은 거나다 맘에 안 들어가만히 있어도 물어뜯을 걸갖다 줘 고맙지 뭐걸레짝 되면 또 딴 얘깃거리갈아타면 되지 뭐대단한 무당 나셨어눈빛만 봐도 척척 알아와플 먹어 너도 한번 씹어 악플 먹어쟤랑 걔랑 사귄대그렇다 카더라내 친구의 사촌의선배의 친구의 사돈이 봤대그렇다 카더라쟤랑 걔랑 싸웠대그렇다 카더라다 뒤집고 엎고 치고아수라 난장판 내놨대아니면 말고야 야 그렇게 막 말해도 돼에이 뭐 어때 안될 건또 뭐야 뭐야그래 뭐걔 걱정해서 뭐 해그래 뭐걔 실드 쳐서 뭐 해그래 뭐 알아서 잘 살겠지쟤랑 걔랑 사귄대그렇다 카더라내 친구의 사촌의선배의 친구의 사돈이 봤대그렇다 카더라쟤랑 걔랑 싸웠대그렇다 카더라다 뒤집고 엎고 치고아수라 난장판 내놨대아니면 말고\n', 'song_id': '30853155', '작사': '종현 (JONGHYUN)', '작곡': '위프리키', '편곡': '위프리키'}
{'title': '나의 사춘기에게', 'artist': '볼빨간사춘기', 'lyrics': '\n나는 한때 내가 이 세상에사라지길 바랬어온 세상이 너무나 캄캄해매일 밤을 울던 날차라리 내가 사라지면마음이 편할까모두가 날 바라보는 시선이너무나 두려워아름답게 아름답던그 시절을 난 아파서사랑 받을 수 없었던내가 너무나 싫어서엄마는 아빠는 다나만 바라보는데내 마음은 그런 게 아닌데자꾸만 멀어만 가어떡해 어떡해 어떡해 어떡해시간이 약이라는 말이내게 정말 맞더라고하루가 지나면 지날수록더 나아지더라고근데 가끔은 너무 행복하면또 아파올까 봐내가 가진 이 행복들을누군가가 가져갈까 봐아름다운 아름답던그 기억이 난 아파서아픈 만큼 아파해도사라지지를 않아서친구들은 사람들은 다나만 바라보는데내 모습은 그런 게 아닌데자꾸만 멀어만 가그래도 난 어쩌면내가 이 세상에밝은 빛이라도 될까 봐어쩌면 그 모든 아픔을내딛고서라도짧게 빛을 내볼까 봐포기할 수가 없어하루도 맘 편히 잠들 수가 없던 내가이렇게라도 일어서 보려고 하면내가 날 찾아줄까 봐아아아아아아아 아아아아아아아아아아아아아아 아아아아아아아얼마나 얼마나 아팠을까얼마나 얼마나 아팠을까얼마나 얼마나 얼마나 바랬을까\n', 'song_id': '30657311', '작사': '안지영', '작곡': '안지영', '편곡': '바닐라맨 (바닐라어쿠스틱)'}
{'title': 'REALLY REALLY', 'artist': 'WINNER', 'lyrics': '\nREALLY REALLY REALLY REALLYOH WAHREALLY REALLY REALLY REALLY어디야 집이야 안 바쁨 나와봐너네 집 앞이야 너에게 하고픈 말이 있어이걸 어떻게 말을 꺼내야 할진 모르겠지만이상한 말 아냐 부담 없이 들어줘지금 내 눈에 제일 아름다운 건 너야 LADY널 향한 내 맘이 돈이면 아마 난 BILLIONAIRE널 좋아해REALLY REALLY REALLY REALLY내 맘을 믿어줘 OH WAHREALLY REALLY REALLY REALLY널 좋아해REALLY REALLY REALLY REALLY내 맘을 받아줘 OH WAHREALLY REALLY REALLY REALLY넌 나 어때멋지게 골인프러포즈 같은 세리머니정해보자 호칭 허니 말고 자기 아님 달링낯간지럽네 상상해봐도긴장돼 필요해 a lot of alcohol덩치는 산만해도 네 앞에선 작아지네oh 내 맘 알까나첫눈에 미끄러지듯이 Falling in love내 맘을 훔친 범인인 건 바로 너너의 미모 질투해 여신도내 심장의 떨림은 진동 brrr치명적인 매력이 날 killin’섹시해 날 자극하는 Hot chili woo오해하지 마 나는 진짜진심으로 채워줄게 너의 빈 잔지금 내 눈에 제일 아름다운 건 너야 LADY널 향한 내 맘이 돈이면 아마 난 BILLIONAIRE널 좋아해REALLY REALLY REALLY REALLY내 맘을 믿어줘 OH WAHREALLY REALLY REALLY REALLY널 좋아해REALLY REALLY REALLY REALLY내 맘을 받아줘 OH WAHREALLY REALLY REALLY REALLY넌 나 어때혹시라도 내가 불편하면 let me know한걸음 뒤로 가 단지 아는 사이로기다릴 수 있어 너도 나를 좋아할 거 같다 말해줘 지금 당장 만나 나 진심으로 네게 할 말이 있어 널 좋아해REALLY REALLY REALLY REALLY내 맘을 믿어줘 OH WAHREALLY REALLY REALLY REALLY널 좋아해REALLY REALLY REALLY REALLY내 맘을 받아줘 OH WAHREALLY REALLY REALLY REALLY넌 나 어때네가 좋아 REALLY REALLY OH YEAH널 좋아해\n', 'song_id': '30341745', '작사': '이승훈', '작곡': 'MINO', '편곡': '강욱진'}
{'title': '짙어져', 'artist': '멜로망스', 'lyrics': '\n널 잊어보려 계속 노력하고 있어괜히 더 즐거운 척시간을 보내는 날 넌 모르겠지행복한 척하며 지내다 보면 언젠가너를 잊게 될 거라 믿으며살고 있는 날 모르겠지내가 노력해봐도 너 때문이라서너는 더 짙어져 가고혼자 남겨진 시간을 보내는 게 이젠내겐 너무 두려운 일이돼버렸단 걸 넌 모르겠지네 꿈을 꾸는 밤이 오는 게 난 두려워이젠 내게 밤이무서워졌다는 걸 너는 모르겠지내가 노력해봐도너 때문이라서 너는 더짙어져 가고너를 그리고노력할수록너는 계속 커져만 가겠지짙어져 가는너를 붙잡고생각할수록너는 계속 커져만 가겠지널 잊어보려 항상 노력하고 있어괜히 더 즐거운 척살아보고 있는 날 넌 모르겠지\n', 'song_id': '30667988', '작사': '김민석', '작곡': '1601', '편곡': '1601'}
{'title': '덜덜덜', 'artist': 'EXID', 'lyrics': "\n알아먹게 Talk 해 다리 떨지 말고왜 아무 말이나 해 그건 어디 말이니어버버Uh 어버버버버버 어버버떨리는 동공 더더더덜머리 굴리는 소리 안 나게 좀 해봐다 티가 나 기가 차뭐가 그리 찔리나지금 웃음이 나와 아 짜증나게내가 뭘 했다고네 머리 다리 팔이 떨려 덜덜덜Yeah 도둑마냥 제 발 저렸지 막쥐 잡듯이 잡아주지 난What you what youwanna do right nowHow stupid littledumb dumb stop now거짓말 다 네가 속인거래한번 하면 또 한대 버릇돼서결국 끝난대옆에선 다 내가 미친 거래너만 속아주고 다 주고 다 주고하지마 자꾸만 나를더 미치게 만들지마그렇게 깊게 가지마더이상 밀어내기 싫다면Why don't you 쉿 ma babyWhy don't you 쉿 ma babyWhy don't you 쉿 ma baby이게 진짜 마지막이야 말해봐미안하다면서뭐가 미안한데미안하다매 다 네 탓이었다매 똑같네그냥 그동안 네가 한 모든 사과기분 참 뭐 같네그럼 난 뭐가 돼 아 참내이제 난 힘들어 그만할래내가 어쩌길 바래나한테 정말 이럼 안돼앞에선 내가 못되게 해도결국 속아주고 다 주고 다 주고하지마 자꾸만나를 더 미치게 만들지마그렇게 깊게 가지마더이상 밀어내기 싫다면Why don't you 쉿 ma babyYour Lips 덜덜덜덜Your Eyes 덜덜덜덜네 머리 허리 다리 모두 다Your Lips 덜덜덜덜Your Eyes 덜덜덜덜네 머리 허리 다리 모두 다하지마 자꾸만나를 더 미치게 만들지마그렇게 깊게 가지마더이상 밀어내기 싫다면Why don't you 쉿 ma baby\n", 'song_id': '30713051', '작사': 'V!VE', '작곡': 'V!VE', '편곡': '신사동 호랭이'}
{'title': '피 땀 눈물', 'artist': '방탄소년단', 'lyrics': '\n내 피 땀 눈물 내 마지막 춤을다 가져가 가내 피 땀 눈물 내 차가운 숨을다 가져가 가내 피 땀 눈물내 피 땀 눈물도 내 몸 마음 영혼도너의 것인 걸 잘 알고 있어이건 나를 벌받게 할 주문Peaches and creamSweeter than sweetChocolate cheeksand chocolate wingsBut 너의 날개는 악마의 것너의 그 sweet앞엔 bitter bitterKiss me 아파도 돼어서 날 조여줘더 이상 아플 수도 없게Baby 취해도 돼 이제 널 들이켜목 깊숙이 너란 위스키내 피 땀 눈물 내 마지막 춤을다 가져가 가내 피 땀 눈물 내 차가운 숨을다 가져가 가원해 많이 많이 많이 많이원해 많이 많이 많이 많이많이 많이원해 많이 많이 많이 많이원해 많이 많이 많이 많이많이 많이아파도 돼 날 묶어줘내가 도망칠 수 없게꽉 쥐고 날 흔들어줘내가 정신 못 차리게Kiss me on the lips lips둘만의 비밀너란 감옥에 중독돼 깊이니가 아닌 다른 사람 섬기지 못해알면서도 삼켜버린 독이 든 성배내 피 땀 눈물 내 마지막 춤을다 가져가 가내 피 땀 눈물 내 차가운 숨을다 가져가 가원해 많이 많이 많이 많이원해 많이 많이 많이 많이많이 많이원해 많이 많이 많이 많이원해 많이 많이 많이 많이많이 많이나를 부드럽게 죽여줘너의 손길로 눈 감겨줘어차피 거부할 수조차 없어더는 도망갈 수조차 없어니가 너무 달콤해 너무 달콤해너무 달콤해서내 피 땀 눈물내 피 땀 눈물\n', 'song_id': '30029173', '작사': '김도훈 (RBW)', '작곡': '김도훈 (RBW)'}
{'title': 'HandClap (영화 `슈퍼배드 3` 삽입곡)', 'artist': 'Fitz & The Tantrums', 'lyrics': "\nTurn it upSomebody save your soulcause you've been sinning in this city I knowToo many troubles allthese lovers got you losing controlYou're like a drug to mea luxury my sugar and goldI want the good lifeEvery good night you're a hard one to holdCause you don't even knowI can make your hands clapSaid I can make your hands clapSomebody save your soulcause you've been sinning in this city I knowToo many troubles allthese lovers got you losing controlYou're like a drug to mea luxury my sugar and goldI want your sex and your affectionwhen they're holdin' you closeCause you don't even knowI can make your hands clapSaid I can make your hands clapEvery night when the stars come outAm I the only living soul aroundNeed to believe you could hold me downCause I'm in need of somethin' good right nowWe could be screamin' till the sun comes outAnd when we wake we'd be the only soundI get on my knees and say a prayerThat I can make your hands clapThat I can make your hands clapTurn it upThat I can make your hands clapMy flesh is searchin' foryour worst and best don't ever denyI'm like a stranger gimme me dangerAll your wrongs and your rightsSecrets on Broadway to the freewayyou're a keeper of crimesFear no conviction grapes of wrathcan only sweeten your wineBut you don't even knowI can make your hands clapSaid I can make your hands clapEvery night when the stars come outAm I the only living soul aroundNeed to believe you could hold me downCause I'm in need of somethin' good right nowWe could be screamin' till the sun comes outAnd when we wake we'd be the only soundI get on my knees and say a prayerThat I can make your hands clapThat I can make your hands clapThat I can make your hands clapThat I can make your hands clapSo can I get a hand clap\n", 'song_id': '8111603'}
{'title': '기름때 (Grease)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n새까만 기름때빠지질 않아 마치 꼭 너 같아네 하얀색 셔츠 위에 새까만 게덕지덕지 붙어있어기분까지 더러워 더러워그래 꼭 너 같아지겹게 끔찍하게 번진 게다 못쓰게 만들어 버린 게너랑 눈 맞춘 게 내 잘못이야내가 날 몰랐었던 게 내 잘못이야I want to clean it upClean it upI want to fix it upFix it up전부 다 없던 걸로 해전부 다 없던 걸로 해내 기억 버려내가 준 것도 다 버려 이미 내겐의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘내 기억 버려내가 준 것도 다 버려 버려줘의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘내가 잘못한 건 없어고르라면 널 안 거널 아는 거미쳤지 미쳤지 내가되풀이해도 뭐 어째뭐가 아깝다고 난 널내가 뭐가 아쉽다고 난 널만나서 후회만후회만 계속해 계속해기회만 있다면전부 다 지울 수 있다면널 아는 걸 널 아는 애들한테다 빌어서라도미쳤지 미쳤지내가 미쳤지 미쳤었지돌리고 싶어 다 돌리고 싶어I want to clean it upClean it upI want to fix it upFix it up전부 다 없던 걸로 해전부 다 없던 걸로 해내 기억 버려내가 준 것도 다 버려 이미 내겐의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘내 기억 버려내가 준 것도 다 버려 버려줘의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘I know I know I knowI know I know I know네가 준 기억도 다 필요 없으니까미운 정 떨어진지도 오래니까Gotta be alone better be alone내 기억 버려내가 준 것도 다 버려 이미 내겐의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘내 기억 버려내가 준 것도 다 버려 버려줘의미 없어진지 오래니까이제 좀 사라져요지우고 싶으니까 이제 좀 사라져 줘\n', 'song_id': '30853156', '작사': '종현 (JONGHYUN)', '작곡': 'Jake K (Full8loom)', '편곡': 'Jake K (Full8loom)'}
{'title': '마지막처럼', 'artist': 'BLACKPINK', 'lyrics': "\n너 뭔데 자꾸 생각나자존심 상해 애가 타얼굴이 뜨겁고 가슴은 계속 뛰어내 몸이 맘대로 안 돼 어지러워넌 한 줌의 모래 같아잡힐 듯 잡히지 않아넌 쉽지 않은 걸 그래서 더 끌려내 맘이 맘대로 안 돼 어이없어지금 너를 원하는내 숨결이 느껴지니널 바라보고 있어도 missing you서툰 날 won’t you set me freeBaby 날 터질 것처럼 안아줘그만 생각해 뭐가 그리 어려워거짓말처럼 키스해줘 내가 너에게마지막 사랑인 것처럼마지막처럼 마-마-마지막처럼마지막 밤인 것처럼 love마지막처럼 마-마-마지막처럼내일 따윈 없는 것처럼Uh I'ma fall in love babyYou gon finna catch meUh give you all of this babyCall me pretty and nastyCause we gonna get it my loveyou can bet it onblack we gon double the stackon them whoaI be the Bonnieand you be my ClydeWe ride or dieXs and Os시간은 흘러가는데 마음만 급해지지내 세상은 너 하나만 missing you서툰 날 won’t you set me freeBaby 날 터질 것처럼 안아줘그만 생각해 뭐가 그리 어려워거짓말처럼 키스해줘 내가 너에게마지막 사랑인 것처럼마지막처럼 마-마-마지막처럼마지막 밤인 것처럼 love마지막처럼 마-마-마지막처럼내일 따윈 없는 것처럼One two three 새로운 시작이야절대 뒤돌아보진 않을 거니까날 너에게 던지면 너는 날 꼭 잡아줘세상은 우릴 꺾지 못할 테니까BLACKPINK in your areaBaby 날 터질 것처럼 안아줘그만 생각해 뭐가 그리 어려워거짓말처럼 키스해줘 내가 너에게마지막 사랑인 것처럼마지막처럼 마-마-마지막처럼마지막 밤인 것처럼 love마지막처럼 마-마-마지막처럼내일 따윈 없는 것처럼 love\n", 'song_id': '30481578', '작사': 'CHOICE37', '작곡': 'Lydia Paek', '편곡': 'TEDDY'}
{'title': 'Take The Dive', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n멈춰버린 숨소리 아마 나도 모르게그때 너를 발견한 순간무수한 우연들이 결국 너란 바다에흘러든 것만 같은 예감I will Take The Dive좁은 욕조가 오늘은 왠지 깊어Singing na na na na na너를 떠올리다가빠져들어 난Take The DiveTake The Dive Woo woo wooTake The Dive Woo눈을 뜨고 꿈을 꿔이제 너란 숨을 쉬어나란 작은 세상이 너와 마주쳤을 때그때 내게 일어난 파장단 한 번의 웃음이 무색했던 내 맘을전부 물들이고도 남잖아I will Take The Dive낯선 조류가 오늘은 왠지 깊어Singing na na na na na잠시 망설이다가뛰어들어 난Take The DiveTake The Dive Woo woo wooTake The Dive Woo눈을 뜨고 꿈을 꿔이제 너란 숨을 쉬어Would you Take The DiveWould you Take The DiveWould you Take The Dive너란 바다에 날 풀어줘오직 너로 채워줘알고 싶어 난 너의 눈이 부신 표면에심해 저편까지도 Oh ITake The DiveTake The Dive Woo woo wooTake The Dive WooOh I will Take The Dive눈을 뜨고 꿈을 꿔이제 너란 숨을 쉬어\n', 'song_id': '30853157', '작사': '서지음', '작곡': 'Royal Dive', '편곡': 'Royal Dive'}
{'title': '꽃이야', 'artist': 'JBJ', 'lyrics': "\nI don't know me eitherYou are in full blossomJust hold me tight 그냥 친한 친군 척 남자 사람 친군 척네 주위를 계속 맴돌기만 해매일 보는 사인데 왜 볼 빨개지는데이상해 말도 못 해 나 왜 이래Everyone loves the things she do중심을 잃어버려 네 옆에선 나도 다시 본 Blossom 어제와는 다르죠또 가끔은 지쳐 너를 생각하면그쯤은 감수해 I`ll be a daydreamer 아슬아슬 위험하게 내 맘 갖고 노는데나 어떡해야 해 더 커져가고 있는데What너는 나의 꽃이야 너는 나의 봄이야계속 피어나니까 감당 안 돼 어떡해 나이제부터는 내가 있잖아안아줄 거야 언제나처음 만난 그 순간부터 넌 나의 꽃이야나의 꽃이야왜 넌 나의 꽃이야 왜왜네 앞에서만 몸치야 Baby네 목소리가 달콤하게 바람에 날려날 끌어안아 줘 난 미쳐 바라 Me like yuhI can't control myself난 미소를 짓네 전화기에널 담아 눈으로 찰칵 셔터너의 갤러리 In my head금지된 선을 이미 넘은 듯 금단의 술을 마신 듯너에게 빠져들어 이미 취했어아슬아슬 위험하게 내 맘 갖고 노는데나 어떡해야 해 더 커져가고 있는데What너는 나의 꽃이야 너는 나의 봄이야계속 피어나니까 감당 안 돼 어떡해 나이제부터는 내가 있잖아안아줄 거야 언제나처음 만난 그 순간부터 넌 나의 꽃이야널 가지고 싶어 다 표현 못 해입술이 맘대로 움직이질 않네없어 너밖에 다 안드로메다에Come closer 내 맘이 네 맘에 닿길후회 없이 직진해What너는 나의 꽃이야 너는 나의 봄이야계속 피어나니까 감당 안 돼 어떡해 나이제부터는 내가 있잖아안아줄 거야 언제나처음 만난 그 순간부터 넌 나의 꽃이야 나의 꽃이야\n", 'song_id': '30844817', '작사': '권현빈', '작곡': 'BULL$EYE', '편곡': 'Brownn'}
{'title': 'Blue', 'artist': '볼빨간사춘기', 'lyrics': '\n음음음음음 yeah 음음음음음So blue blue blue blue blue yeah blue blue blue blue blue 지금 내 맘의 색깔은 blue 기분이 별로 안 좋아 알잖아 나 좀 예민해 네게만 참 까다롭잖아잘 지냈냐 물어보네 Do you 난 아냐 지금보다 조금 더 나아졌으면 해미안해 미워해 조금은 좋아해 좀 야윈 모습이 안쓰럽기는 해도나는 또 아직도 네 눈을 마주칠 수 없는 걸 넌 여전히 내가 참 미워 보이잖아파랗게 blue blue 우리가 칠해지네 서로의 맘도 파랗게 멍들어갈 때내 맘은 true true 너와 함께 있을 땐 사랑받던 모습이 그토록 아름다웠는데음음음음음 yeah 음음음음음So blue blue blue blue blue yeah blue blue blue blue blue 지금 내 맘의 색깔은 blue 기분이 별로 안 좋아 알잖아 나 좀 피곤해 네게만 참 까다롭잖아잘 지냈냐 물어봐도 Do you 난 아냐 지금보다 조금 더 아파했으면 해미안해 미워해 아직 널 좋아해 네 지친 모습이 안쓰럽기는 해도나는 또 아직도 네 눈을 마주칠 수 없는 걸 넌 여전히 내가 참 미워 보이잖아파랗게 blue blue 우리가 칠해지네 서로의 맘도 파랗게 멍들어갈 때내 맘은 true true 너와 함께 있을 땐 사랑받던 모습이 그토록 아름다웠는데미안해 미워해 조금은 좋아해미안해 미워해 아직 널 좋아해파랗게 blue blue 우리가 칠해지네 서로의 맘도 파랗게 멍들어갈 때내 맘은 true true 너와 함께 있을 땐 사랑받던 모습이 그토록 아름다웠는데음음음음음 yeah 음음음음음So blue blue blue blue blue yeah blue blue blue blue blue \n', 'song_id': '30657308', '작사': '안지영', '작곡': '안지영', '편곡': '바닐라맨 (바닐라어쿠스틱)'}
{'title': '빨간 맛 (Red Flavor)', 'artist': 'Red Velvet (레드벨벳)', 'lyrics': '\n빨간 맛 궁금해 Honey깨물면 점점 녹아든 스트로베리 그 맛코너 캔디 샵 찾아 봐 Baby내가 제일 좋아하는 건 여름 그 맛야자나무 그늘 아래 졸고 싶고뜨거운 여름밤의 바람은 불고너무 쉽게 사랑 빠져 버릴 나인틴우린 제법 어울리고 또 멋져좋아 첫눈에 반해 버린네가 자꾸만 생각나내 방식대로 갈래빨간 맛 궁금해 Honey깨물면 점점 녹아든 스트로베리 그 맛코너 캔디 샵 찾아 봐 Baby내가 제일 좋아하는 건 여름 그 맛일곱 개의 무지갯빛 문을 열어너의 세상은 짜릿해 멋있어태양보다 빨간 네 사랑의 색깔내가 가질래 내 멋대로 할래날 봐 넌 뭘 생각하는데오늘 뭘 할 수 있을까내 맘대로 상상해빨간 맛 궁금해 Honey깨물면 점점 녹아든 스트로베리 그 맛코너 캔디 샵 찾아 봐 Baby내가 제일 좋아하는 건 여름 그 맛복숭아 주스 스윗 앤 사워 믹스 Mood 네게 주고픈 칵테일을 Brew RED귓속이 쨍 코가 맹상상 그 이상 기분 Up and bang REDBet you wanna bet you wanna dance like this외쳐보자 좋아해요 솔직히긴장해 땀이 뚝뚝 귀엽지사랑에 빠져 그을려 우린 RED RED Ah말 안 해도 알아주면 안 돼내 맘은 더 커져 가는데다 흘려버린 아이스크림같이이러다 녹을지 몰라그러니 말해 그래 그래 말해 그러니 말해 그래 그래 말해 너의 색깔로날 물들여줘 더 진하게 강렬하게빨간 맛 궁금해 Honey깨물면 점점 녹아든 스트로베리 그 맛코너 캔디 샵 찾아 봐 Baby내가 제일 좋아하는 건 여름 그 맛내가 제일 좋아하는 건 여름의 너\n', 'song_id': '30512671', '작사': 'kenzie', '작곡': 'Ludwig Lindell', '편곡': 'Caesar & Loui'}
{'title': '사람 구경 중 (Sightseeing)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n저 사람들은 어딜 간대뭐가 저리 바빠 꼭혼이 빠진 것 마냥고갤 푹 고갤 푹 또는 폰에시선 고정야 앞 좀 봐 위험 위험해대낮 버스 정류장앞에 우글우글 대는 게 막 징글징글해 꼭 찡그린 고양이 표정다들 그리 어디로 간대행선진 또 어딘데 궁금하잖아넌 어딜 가는데끌려가는 듯한 꼴이 칙칙해얼굴이 두 다리 무거워 보여 BabeWhoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 같이 가줘Whoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘저기 저 아가씨는 바빠날 볼 생각이 전혀 없어시선이 돌아간 순간에 야 야 차 차야 앞 좀 봐 위험 위험해대낮 버스 정류장앞에 우글우글 대는 게 막 징글징글해 꼭 찡그린 고양이 표정다들 그리 어디로 간대행선진 또 어딘데 궁금하잖아넌 어딜 가는데끌려가는 듯한 꼴이 칙칙해얼굴이 두 다리 무거워 죽겠나 봐Whoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 같이 가줘Whoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘Whoa Whoa Whoa WhoaWhoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 같이 가줘Whoa Whoa 쟤 좀 봐 쟤 좀 봐 어디 가 어디 가 나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘Whoa Doo loo doo doo dooDoo loo doo doo doo나도 데리고 가줘\n', 'song_id': '30853158', '작사': '종현 (JONGHYUN)', '작곡': '위프리키', '편곡': '위프리키'}
{'title': '갖고 싶어', 'artist': 'Wanna One (워너원)', 'lyrics': '\n너의 이름까지 갖고 싶어 너의 눈빛 작은 손짓 하나까지너의 기억까지 안고 싶어너의 시간 모든 순간까지 다 갖고 싶어숨겨왔던 마음이 자꾸만 새어 나와너를 보면 마주 보면어지러워 너무나 예쁜 걸Wanna be your love 자꾸 나의 마음이 No너를 보면 마주 보면마음대로 안 돼너의 이름까지 갖고 싶어너의 눈빛 작은 손짓 하나까지 다너의 기억까지 안고 싶어너의 시간 모든 순간까지 다매일 하루의 끝에 시답지 않은 얘길 하고 싶은데나의 계절의 끝에서 너와의 얘길 담고 싶어네 마음을 갖고 싶어갖고 싶어I wanna be yours I wanna be yours Girl아무도 비교할 수 없어 나만의 World내 눈동자에는 너만 담고 싶어지금 이 순간도 너를 갖고 싶어바보처럼 혼자 속삭이다가 Be afraid 네 앞에 서면 자꾸 작아져 왜너를 보면 마주 보면내 옆자리엔 You 너였으면 해너의 이름까지 갖고 싶어너의 눈빛 작은 손짓 하나까지 다너의 기억까지 안고 싶어 너의 시간 모든 순간까지 다매일 하루의 끝에시답지 않은 얘길 하고 싶은데나의 계절의 끝에서너와의 얘길 담고 싶어네 마음을 갖고 싶어너만 생각하면 내 심장이 떨려서말하고 싶지만 이리 오래 걸렸어 Baby 너에게 해주고 싶은 말들이 너무나 많아멈춰있던 내 심장을 네가 깨웠어수백 번 다시 생각해도 내겐 오직 너너도 내가 좋다면 지금 당장 말해줘You know what I mean너란 아이를 Dreaming맘을 열어줘 내게 더 다가와매일 하루의 끝에시답지 않은 얘길 하고 싶은데나의 계절의 끝에서너와의 얘길 담고 싶어네 마음을 갖고 싶어\n', 'song_id': '30725483', '작사': 'Party in My Pool', '작곡': '정호현 (e.one)', '편곡': '정호현 (e.one)'}
{'title': '눈 떠보니 이별이더라', 'artist': '포맨', 'lyrics': '\n분명 나는 꿈을 꾼 거다눈 떠보니 이별이더라휴대폰을 확인해 봤더니다시 봐도 이별이더라헛웃음만 흘러나왔고두 다리는 풀려 버렸고문득 스친 네 얼굴 생각나 눈물이하염없이 쏟아지는데대체 무슨 짓을 한 건데엎질러진 물에난 젖은 채로 꼼짝 못하고그 수많은 이별 뒤에도넌 분명히 사랑이었다 정말내 옆에 있었잖아 늘 여기 있었잖아네가 날 떠나가면 그냥 가버리면이런 식이면 나 곤란한데눈 떠보니 이별이더라이건 절대 현실이 아니야눈 감으면 꿈이 될 거야애써 부정해봐도 이별이 맞잖아눈물마저 말라버리고네 이름만 중얼거리고움직이지 못하고웅크린 채 너만 외치고 그 수많은 이별 뒤에도넌 분명히 사랑이었다 정말내 옆에 있었잖아 늘 여기 있었잖아네가 날 떠나가면 그냥 가버리면이런 식이면 나 곤란한데꿈만 같던 사랑도다 이별하면 현실이야알람 하나 없이 깨어나한 번만 더 기회를 줘다시 하면 잘할 텐데내가 바보 같아 화가 나참을 수가 없다그 수많은 이별 뒤에도당연하게 이별이 온다 정말가슴을 찢어 놔도 네가 날 짓밟아도나 아닌 딴 사람과 평생 사랑해도나는 너 아니면 곤란한데평생 나는 너 아니면 안 되는데눈 떠보니 이별이더라\n', 'song_id': '30690674', '작사': '이수빈', '작곡': 'KingMing', '편곡': 'KingMing'}
{'title': 'WHERE YOU AT', 'artist': '뉴이스트 W', 'lyrics': '\nWHERE YOU AT네가 없는 사이에 그리워진 마음은 파랗게 또 멍들고상처 난 마음은 아프지 않아서고칠 생각하지 않아어렵사리 오늘 꿈에서라도 널 YAYAYA세상 끝에서라도 널 YAYAYA손을 마주잡을 수 있다면내일이 없어도 난 괜찮아YEH 이리저리 또 헤매고 널 찾아너를 찾아서 뛰어봐도 내 방 안원해 원해 원해 매일 더너를 찾고 있는데 WHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU AT아무렇지 않아 아무렇지 않아매일 나를 속이고잊을 수 없다면 기억하고 싶어너는 나의 한 조각끝이 없이 좁은 터널 속에 갇힌 난아무것도 보이지가 않는 내 맘은 점점 물든 기분손을 뻗어 잡히지 않는다고 해도이미 커져버린 넌 환상이래도 난 계속해서 쫓아YEH 이리저리 또 헤매고 널 찾아너를 찾아서 뛰어봐도 내 방 안원해 원해 원해 매일 더너를 찾고 있는데 WHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU ATWHERE YOU AT습관이란 게 무섭긴 한가 봐눈만 뜨면 네 흔적부터 찾아네 목소리를 잊고 싶지 않아서마지막에 부른 내 이름을 따라 부른다WHERE YOU ATWHERE YOU AT\n', 'song_id': '30661885', '작사': 'BUMZU', '작곡': 'Royal Dive', '편곡': 'BUMZU'}
{'title': '어떤 기분이 들까 (I`m So Curious)', 'artist': '종현 (JONGHYUN)', 'lyrics': "\n대체 어떤 기분이 들까 너와 눈을 맞추면대체 어떤 기분이 들까 너와 손을 잡으면대체 어떤 기분이 들까 너와 입을 맞추면I'm So Curious Curious curious Yeah yeah너의 눈을 봐 까맣게 빛나움직이지 마 온전하게 널담아 둘래 난 싱겁게 굴긴 싫어너의 손 덥석 잡고 싶어 난네 뒷 목덜미 네 개미허리전부 가까이서 볼래 욕심이 나는 걸 나는 다자세히 보고 싶어 샅샅이 알고 싶어 널너와 눈 자꾸 마주칠 때면스치듯 네 손끝 날 지나쳐 갈 때면괜히 서운해져 일초라도 더살을 맞대줘 떼지 말아줘네 모든 게 난 궁금한데 넌안 그런가 봐 Baby 나만 그래대체 어떤 기분이 들까 너와 눈을 맞추면대체 어떤 기분이 들까 너와 손을 잡으면대체 어떤 기분이 들까 너와 입을 맞추면I'm So Curious Curious curious Okay baby떨어지지 마 내게서 멀어지지 말아줘꼭 강아지 혼자 남겨진 듯이바들바들 떠는 꼴이 안절부절 하는 꼴이 안쓰럽잖아Take care of me Baby care about me또 나만 그래 여유 부린 건 항상 네 쪽 Baby가만히 꼭 네 다리가 이뻐서 또 정신 못 차리겠어너와 눈 자꾸 마주칠 때면스치듯 네 손끝 날 지나쳐 갈 때면괜히 서운해져 일초라도 더살을 맞대줘 떼지 말아줘네 모든 게 난 궁금한데 넌안 그런가 봐 Baby 나만 그래대체 어떤 기분이 들까 너와 눈을 맞추면대체 어떤 기분이 들까 너와 손을 잡으면대체 어떤 기분이 들까 너와 입을 맞추면I'm So Curious Curious curious Okay baby어색하지 나도야 그래도뒷걸음치지 마 도망치지 말아줘네 발은 내 발등 위에 네 손은 내 허리 위에 자릴 잡아줘 YeahWoo woo Stay chill baby 긴장은 풀어줘 Lady이 공간의 분위길 느껴 내게 맡겨 Babe대체 어떤 기분이 들까 너와 눈을 맞추면대체 어떤 기분이 들까 너와 손을 잡으면대체 어떤 기분이 들까 너와 입을 맞추면I'm So Curious Curious curious Okay baby대체 어떤 기분이 들까대체 어떤 기분이 들까대체 어떤 기분이 들까대체 어떤 기분이 들까대체 어떤 기분이 들까Curious curious\n", 'song_id': '30853161', '작사': '종현 (JONGHYUN)', '작곡': '진바이진', '편곡': '진바이진'}
{'title': '미안해', 'artist': '양다일', 'lyrics': '\n습관처럼 떠오르던눈에 아른거리던 네 모습이더는 그려지지 않아거짓뿐이었던 너의 말과너도 모르는 너의 모습들을더는 원치 않아단 한 번뿐인 이별에도 말하지 못한너의 진심을 이젠 다 알 것 같은데미안해 더는 널 바라보지 않아미안해 더는 나 후회하지 않아다시 널 마주할 그 순간에도널 사랑하지 않아 말할 수 있어수화기 너머 들리는지친 날 위로하던 네 목소리더는 그려지지 않아함께 쌓았던 추억과그 많던 말들이 아쉬워서전하지 못한 말들이미안해 더는 널 바라보지 않아미안해 더는 나 후회하지 않아다시 널 마주할 그 순간에도널 사랑하지 않아 말할 수 있어어색하게 만난 우리 시작도처음 고백했던 그 순간들도다 어제 같은 일인데누굴 만나 사랑한다는 게너를 만나 내가 변해간단 게이젠 없어미안해 더는 널 사랑하지 않아미안해 더는 나 후회하지 않아힘든 시간들에 지쳐갈 때도이렇게 해야만 내가 편할 것 같아\n', 'song_id': '30809895', '작사': '정키', '작곡': '정키', '편곡': '정동환'}
{'title': 'Best Of Me', 'artist': '방탄소년단', 'lyrics': "\nWhen you say that you love me난 하늘 위를 걷네영원을 말해줘 just one more timeWhen you say that you love me난 그 한 마디면 돼변하지 않는다고 just one more time넌 내게 이 세계의 전부 같아더 세게 아프게 날 꽉 껴안아우리가 나눈 somethingAnd you can't make it nothing잊지 않아줬으면 해 넌 내하루하루여름 겨울넌 몰라도You got the best of meYou got the best of meSo please just don't leave meYou got the best of me나도 나의 끝을 본 적 없지만그게 있다면 너지 않을까다정한 파도고 싶었지만니가 바다인 건 왜 몰랐을까어떡해 너의 언어로 말을 하고또 너의 숨을 쉬는데I'll be you 날 쥐고 있는 너난 너의 칼에 입맞춰그러니 take my hand right now이런 내가 믿기지 않아속으로만 수천 번은 더 말했었던 그 말그대는 날 떠나지 마You got the best of meYou got the best of me꿈인지 현실인지는 딱히 중요치 않지 그저 니가 내 곁에 있다는 게Thanks하루하루여름 겨울넌 몰라도You got the best of meYou got the best of meSo please just don't leave meYou got the best of me넌 나의 구원 넌 나의 창난 너만 있으면 돼You got the best of me니가 필요해So please just don't leave meYou got the best of me비가 내리던 나눈이 내리던 나모든 불행을 멈추고천국을 데려와쉽게 말하지 마너 없는 난 없어넌 내 best of meThe best of me그냥 나에 대한 확신을 줘그게 내가 바란 전부이니까우리의 규율은 없다 해도사랑하는 법은 존재하니까Who got the best of meWho got the best of me누구도 몰라 but I know me내 최고의 주인인 걸 넌You got the best of meYou got the best of meSo please just don't leave meYou got the best of me넌 나의 구원 넌 나의 창난 너만 있으면 돼You got the best of me니가 필요해So please just don't leave meYou got the best of meWhen you say that you love me난 하늘 위를 걷네영원을 말해줘 just one more timeWhen you say that you love me난 그 한 마디면 돼변하지 않는다고 just one more time \n", 'song_id': '30637983', '작사': 'ADORA', '작곡': 'ADORA'}
{'title': '하루만이라도 (Just for a day)', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n하루만이라도 Oh 하루만이라도Oh oh Oh oh이러지 마 자꾸 나타나 왜끝났잖아 다 지난 일인데눈을 떠봐도 감아도꿈을 꾸는 순간에도 난 너야다시는 널 잊진 못한다 해도어제가 또 내일이 된다 해도하루만이라도 Oh 하루만이라도Oh oh Oh oh하루만이라도 제발 내 하루 속에서네가 죽었으면 좋겠어하루만이라도 Oh 하루라도난 없잖아 이미 네 오늘엔잘 알잖아 난 단 하루도 안 된단 걸취하고 비틀대기대고픈 순간조차 난 아냐다시는 날 보진 못한다 해도내일이 또 어제가 된다 해도하루만이라도 Oh 하루만이라도Oh oh Oh oh하루만이라도 제발 네 하루 속에서내가 살아나면 좋겠어하루만이라도 Oh 하루라도단 하루라도다시는 만나지 못한다 해도우리 서로 다른 내일이어도하루만이라도 Oh 하루만이라도Oh oh Oh oh하루만이라도 제발 이 하루 속에서우리 함께라면 좋겠어하루만이라도 Oh 하루라도 YeahHey-ey 하루라도하루만이라도 제발 이 하루 속에서우리 함께라면 좋겠어하루만이라도 Oh 하루라도\n', 'song_id': '30853160', '작사': '전간디', '작곡': 'Chris Wahle', '편곡': 'Chris Wahle'}
{'title': 'Sentimental', 'artist': '종현 (JONGHYUN)', 'lyrics': '\n날 갖고 놀든 말든 상관 안 해 사실뭐라든 너라면 난 그냥 좋았어 Hey혼자서 땅치고 벽치고 난리 법석 떨었지 옛날엔그래도 내 옆이 너라서 좋았어 Uh uh가만히 눈을 감아보면 네가가만히 가만히 내 옆에 있을 것 같은데쓸쓸히 내 맘이 축 처지면 네가내 어깰 토닥토닥 거릴 것 같은데Sentimental 해 나 Sentimental 해너 없는 내 방은 텅 비어서 Sentimental 해몇 센티 안에 네가 누워 있던 게마냥 엊그제 같은데Sentimental 해 너 없는 내 방 안은밥이 넘어가는 걸 보면 그래도 몸 챙기는 걸 보면괜히 이러는가 싶다가도 또 웃는 널 보면 흔들려기분 탓이겠지 뭐 너도 다 잊고 지낼 텐데 뭐별거겠어 내가 기억이나 나겠어가만히 눈을 감아보면 네가가만히 가만히 내 옆에 있을 것 같은데쓸쓸히 내 맘이 축 처지면 네가내 어깰 토닥토닥 거릴 것 같은데Sentimental 해 나 Sentimental 해너 없는 내 방은 텅 비어서 Sentimental 해몇 센티 안에 네가 누워 있던 게마냥 엊그제 같은데Sentimental 해 너 없는 내 방 안은나도 변한 건 딱히 없어너도 여전하겠지 어디 가겠어돌아가고 싶은 건 네가 그리워진 건 아닌데Sentimental 해 나 Sentimental 해너 없는 내 방은 텅 비어서 Sentimental 해몇 센티 안에 네가 누워 있던 게마냥 엊그제 같은데Sentimental 해 너 없는 내 방 안은\n', 'song_id': '30853162', '작사': '종현 (JONGHYUN)', '작곡': 'Jake K (Full8loom)', '편곡': 'Jake K (Full8loom)'}
{'title': '여보세요', 'artist': 'NU`EST', 'lyrics': '\n여보세요 밥은 먹었니 어디서 뭐 하는지 걱정되니까  Tell me baby where you at 여보세요  Call me baby I be there Wherever you are I be there 여보세요 Pick up the phone girl Cuz I gotta be there 차가 막히는지  늦을 건가 봐 급한 맘에 배터리는 또  깜빡 하셨나 봐 나는 또 왠지 비가 올 것 같애  고민을 하다가 너를 좀 더 빨리 보고 싶은 맘에  일찍 데릴러 나가 깜짝 놀라겠지  날 보면 좋아하겠지 길이 엇갈리지  않게 더 달려야겠지 저 멀리 니 모습  보이는데 왜 난 전활 걸어 한다는  말이 결국엔 여보세요 밥은 먹었니 어디서 뭘 하는지  걱정되니까 여보세요  왜 아무 말 못하니 여보세요 여보세요널 데릴러 왔어  비가 올까 봐 혼자 쓸쓸히  빗속을 걸을까 봐  집 앞이야 니가 보여  누구랑 있나 봐 솔직히 말 못했어  그럼 널 잃을까 봐 나도 알아 내 행동 비겁해 비겁하다 놀려도  난 절대 못 가 더는 이런 내 맘 알까 너는 네게 가는 길이  내게 왜 지옥행 같이 느껴져야 되는건지 이건 말이 안돼 니 외로움 달래 준건 난데 어서 말해 제발  아무 사이 아니라고  왜 난 안돼 한 번 해봐  아무 말이라도 지금 너 거기서 뭐하니 지금 널 멀리서 멍하니 바라보는 내가  느껴지지 않니 하고픈 말은 다 내일 해 미안하단 말도 내일 해 자꾸 어딜 봐 바로 여기가  니가 있어야 할 자린데 여보세요 밥은 먹었니어디서 뭘 하는지 걱정되니까여보세요 왜 아무 말 못하니여보세요 여보세요널 보고 싶었어 비가 오니까 비가 내리니까너와 걷던 거리를 걷다 보니까 죽겠으니까집 앞이야 보고 싶어 너는 아닌가 봐솔직히 미치겠어 너 아님 안되나 봐Baby I can’t let you go 밥은 먹었니I only think about you girl What would I be without you girl 어디서 뭐 하는지Don’t tell me lies Don’t say goodbye I just wanna let you know 왜 아무말 못하니I only think about you girl What would I be without you girlWhat would I be without you girl여보세요\n', 'song_id': '4032981', '작사': '손주영', '작곡': '시우', '편곡': 'G-Slow'}
{'title': 'Rewind', 'artist': '종현 (JONGHYUN)', 'lyrics': '\nUh Rewind RewindUh Rewind뭘 하든 간에 시간은 가네아 피곤해 물 한잔할게 Uh뭘 하든 간에 시간은 가네아 피곤해 바닥에 뭐 있네뭘 하든 간에 시간은 가네축축해 좀 닦아야겠네 Uh뭘 하든 간에 눈이 무겁네Uh 긴장할게 너도 집중해 UhRewind Rewind RewindRewind Rewind Rewind RewindOne Two Three Rewind하나 둘 셋 다시 또Eins Zwei Drei Wieder RewindUn Deux Trois Encore Rewind뭘 하든 간에 시간은 가네 Uh뭘 하든 간에 시간은 가네아 시끄러뭘 하든 간에 시간은 가시간은 가 시간은 가네뭘 하든 간에 시간은 가네한 잔만 더 정신이 없네 Uh뭘 하든 간에 시간은 가네뻐근해 오른쪽 어깨 Uh뭘 하든 간에 시간은 가네네가 뭐라 하든 간에 Uh뭘 하든 간에네가 뭐라 하든 간에Rewind Rewind RewindRewind Rewind Rewind RewindOne Two Three Rewind하나 둘 셋 다시 또이치니산모우잇까이다케모우잇까이다케Uno Dos Tres De nuevo RewindRewindRewind Rewind RewindRewind Rewind Rewind RewindOne Two Three Rewind하나 둘 셋 다시 또Eins Zwei Drei Wieder RewindUn Deux Trois Encore RewindOne Two Three Rewind하나 둘 셋 다시 또이치니산모우잇까이다케모우잇까이다케Uno Dos Tres De nuevo Rewind\n', 'song_id': '30853159', '작사': '종현 (JONGHYUN)', '작곡': 'IMLAY', '편곡': 'IMLAY'}
{'title': '매일 듣는 노래 (A Daily Song)', 'artist': '황치열', 'lyrics': '\n힘든 하루 끝에 집 앞에거리를 서성이다돋아나는 이 공허함에 그 노래를 um나도 모르게 또 이렇게흥얼거리고 있어아마 너를 애타게 너를 부르듯이세상에서 이 노래가제일 좋다며 들려주던함께 듣던 노래 너무 슬픈 이 노래매일 듣는 이 노래가 또매일 울려 이 노래가 널떠올리게 만들어다 우리 얘기만 같아서아무리 귀를 막아봐도자꾸 맴돌아듣고 싶지 않아 몸부림쳐도매일 듣는 노래시간이 지나도 이 노랜잊혀지질 않았어가사 하나 멜로디까지 선명해서네 앞에서 불러주려매일 매일 혼자 연습했던함께 듣던 노래 가슴 아픈 이 노래매일 듣는 이 노래가 또매일 울려 이 노래가 널떠올리게 만들어다 우리 얘기만 같아서아무리 귀를 막아봐도자꾸 맴돌아듣고 싶지 않아 몸부림쳐도매일 듣는 노래딴 얘기 같던 노랫말은곧 우리가 됐고그렇게 남은 건 망가진 하루들아주 작은 방 홀로틀어 놓은 이 노래로조심스레 다시 널 불러본다매일 듣는 이 노래가 또매일 울려 이 노래가 널떠올리게 만들어모두 우리 추억들만 같아서아무리 귀를 막아봐도자꾸 맴돌아듣고 싶지 않아 몸부림쳐도매일 듣는 노래\n', 'song_id': '30467550', '작사': '한울', '작곡': '한길', '편곡': '한길'}
{'title': '있다면', 'artist': '뉴이스트 W', 'lyrics': '\n있다면 말할 수 있다면머리카락처럼 자라버린 그리움을 있다면 또 볼 수 있다면저 밤하늘보다 까만 두 눈을있다면 지금까지 놓친 필름 속에 있다면 지나갔던 우리 추억 속에빠져 헤엄쳐 향기는 진하게 배여서그런지 허전함은 내게 배가 되었어떠나 보내고 나서 널 생각해 봤자미련하게도 아직 난 꿈인 것 같아 너의 빈자리 그 자린 계속 비워둘게 안녕이란 말은 잠시 넣어둘래I wanna wanna turn back the time we had별처럼 쏟아지는 기억들그 반짝반짝 거리는 시간 속을헤매다 지쳐 휘청거리는 날닿을 수 있다면 얼마나 좋을까꿈에서라도 if i could stay one more night소설처럼 아니 거짓말처럼 널 다시 만나 활짝 웃을 수 있다면다른 길을 걸어도 시간은 같이 가 다른 풍경을 봐도 하늘은 같이 봐 함께 그려졌었던 도화지에 너란 색 채워지지 않았어 지금 이 그림에 널 다시 볼 수 있다면 너와 웃을 수가 있다면 이게 꿈이라서 손 잡을 수가 있다면 얼마나 좋을까 놓지 않을 텐데 안녕이란 말은 잠시 넣어둘래I wanna wanna go back to you tonight숨처럼 참기 힘든 추억들 또 어느 샌가 피어난 연기 되어내 눈을 가려 휘청거리는 날널 그때에 널 다시 만날 수만 있다면닿을 수 있다면 얼마나 좋을까꿈에서라도 if i could stay one more night소설처럼 아니 거짓말처럼 널 다시 만나 활짝 웃을 수 있다면다시 한번 같이 걸어갈 수 있다면 아름답던 너의 목소리가 잊혀지지 않았어 있다면 웃는 너의 얼굴이 내 기억 속에 생생하게 남아 있어 있다면I miss you I miss you 네가 정말 보고 싶어있다면 돌릴 수 있다면마치 영화처럼 다시 처음 그 자리로 있다면 내 옆에 있다면마치 이 모든 게 아픈 꿈처럼\n', 'song_id': '30543235', '작사': 'JR (뉴이스트)', '작곡': '최진경', '편곡': '최진경'}
{'title': '바람이 불었으면 좋겠어', 'artist': '길구봉구', 'lyrics': '\n웃는 모습이 너무 아름다운  그런 너를 기억하면서 괜찮아 넌 잘할거라 말하던  또 그런 너를 기억하면서 뭐가 그리 내 눈에 깊이 박혔는지 너무 선명해서 이젠  보낼수가 없잖아 바람이 불었으면 좋겠어 널 잊어내도록 널 씻어 내도록 바람이 불었으면 좋겠어 남은  마음까지도 멀리멀리  날아갈 수 있도록어느새 너의 얼굴을 떠올려 또 그런 나를 바라보면서 뭐가 그리 내눈에 깊이 박혔는지 너무 선명해서 이젠  보낼수가 없잖아 바람이 불었으면 좋겠어 널 잊어내도록 널 씻어 내도록바람이 불었으면 좋겠어 남은 마음까지도 멀리멀리 날아갈 수 있도록엉켜버린 나의 마음이 다시금 너로 제자릴 찾아가 워머릴 흔들어봐도 억지로 다른 생각을 해도 나는 너만내얘길 들었으면 좋겠어 닿을 수 있도록 널 볼 수 있도록내얘길 들었으면 좋겠어 흔들 수 있도록 날 볼 수 있도록바람이 불었으면 좋겠어 내 맘 전해지도록 너에게로 다시 갈수있도록\n', 'song_id': '4383833', '작사': '길구봉구', '작곡': '길구봉구', '편곡': 'Sweetch'}
{'title': '왜 날', 'artist': '인피니트', 'lyrics': '\n아무리 애써도 잠이 오질 않아그대 없는 시간 하나도 의미 없죠전부 사라질까 가둬놓은 내 맘을그대는 모르죠그대와의 만남 사랑인 걸 알았죠그대와 입맞춤 꿈꾸는 것 같았죠저 바람에 흩어져버린밤하늘의 별들도내 마음 모르죠왜 날 사랑했나요왜 나를 떠나갔나요내 눈을 보고 또 웃고매일 그리워하고왜 나를 안아줬나요그대는 왜 나 없이어떻게 괜찮을 수 있죠날 바라보던 눈 속에다른 사람을 담아또 사랑을 말하네요겨우 잠이 들죠 꿈속에서 그대가내게 말을 하죠 날 사랑하고 있죠저 하얗게 부서져버린구름이 걷힐 때쯤그대가 보고 싶죠왜 날 사랑했나요왜 나를 떠나갔나요내 눈을 보고 또 웃고매일 그리워하고왜 나를 안아줬나요그대는 왜 나 없이어떻게 괜찮을 수 있죠날 바라보던 눈 속에다른 사람을 담아또 사랑을 말하네요이렇게 아쉬운 마음 되뇌어 보아도그대는 다시 내게 오지 않죠다른 사람 곁에서그대 행복해도 돼요나만 아플게요 그댄 행복해줘요사랑했었던 그대가 나를 떠나가요내 눈을 보고 또 웃고매일 그리워하던그대가 나를 떠나요왜 그대가 없다는 게이렇게 아플 수가 있죠얼마나 아파야그대를 잊을 수 있는 건지그댈 잊고 싶지 않아 아직 난\n', 'song_id': '30824605', '작사': 'SEION', '작곡': 'SEION', '편곡': 'SEION'}
{'title': '뻔한 이별 (PROD. 13)', 'artist': '소유 (SOYOU)', 'lyrics': '\n철없던 짧았던 하지만 뜨거웠던그래서 힘들었던 뻔한 이별 얘기한번씩 생각나고조금씩 잊혀지겠지근데 내 시간이 멈췄어오늘 하루야 빨리 좀 가주라혼자 되뇌이다몇 시간 같은 몇 분 보내아직 아파야 한대 한동안 그렇대그래야 널 잊을 수 있대그런 말이 싫어 또 한번 울고허전한 마음에 밤새너를 불러보다가 함께 잠이 든다철없건 짧았건 뻔하진 않은 이별과잊은 듯 아닌 듯 조금은 무뎌진 듯어제보단 무덤덤 애써 지워보려누구라도 만나보면위로가 되진 않을까바쁘게 집을 나섰어텅 빈 가슴은 채워지질 않고괜찮은 척 하면울컥하며 다시 니 생각이 나아직 아파야 한대 한동안 그렇대그래야 널 잊을 수 있대그런 말이 싫어 또 한번 울고허전한 마음에 밤새너를 불러보다가 함께 잠이 든다철없건 짧았건 뻔하진 않은 이별과어디를 가도 거기서 뭘 해도너와 함께했던 순간이자꾸 돌아와서아직 아파야 한대 한동안 그렇대그래야 널 잊을 수 있대그런 말이 싫어 또 한번 울고허전한 마음에 밤새너를 불러보다가 함께 잠이 든다철없건 짧았건 뻔하진 않은 이별과\n', 'song_id': '30725643', '작사': '13', '작곡': '13', '편곡': '13'}
{'title': '어디에도', 'artist': '엠씨더맥스', 'lyrics': '\n차가워진 눈빛을 바라보며이별의 말을 전해 들어요아무 의미 없던 노래 가사가아프게 귓가에 맴돌아요다시 겨울이 시작되듯이흩어지는 눈 사이로그대 내 맘에 쌓여만 가네떠나지 말라는그런 말도 하지 못하고고개를 떨구던 뒷모습만그대 내게 오지 말아요두 번 다시 이런 사랑 하지 마요그댈 추억하기보단 기다리는 게부서진 내 맘이 더 아파와다시 누군가를 만나서결국 우리 사랑 지워내도행복했던 것만 기억에 남아나를 천천히 잊어 주기를아무것도 마음대로 안 돼요아픔은 그저 나를 따라와밤새도록 커져 버린 그리움언제쯤 익숙해져 가나요많은 날들이 떠오르네요우리가 나눴던 날들애써 감추고 돌아서네요떠나지 말라는그런 말도 하지 못하고고개를 떨구던 뒷모습만그대 내게 오지 말아요두 번 다시 이런 사랑 하지 마요그댈 추억하기보단 기다리는 게부서진 내 맘이 더 아파와다시 누군가를 만나서결국 우리 사랑 지워내도행복했던 것만 기억에 남아나를 천천히 잊어 주기를부를 수도 없이 멀어진 그대가지나치는 바람에도 목이 메어와어디에도 그대가 살아서우린 사랑하면 안 돼요다가갈수록 미워지니까행복했던 것만 기억에 남아나를 천천히 잊어 가기를사랑했던\n', 'song_id': '8033528', '작사': '이수 (엠씨 더 맥스)', '작곡': '이수 (엠씨 더 맥스)', '편곡': '김재현'}
{'title': '팔레트 (Feat. G-DRAGON)', 'artist': '아이유', 'lyrics': "\n팔레트 (Feat. G-DRAGON)이상하게도 요즘엔 그냥 쉬운 게 좋아하긴 그래도 여전히 코린 음악은 좋더라Hot Pink 보다 진한 보라색을 더 좋아해또 뭐더라 단추 있는 Pajamas Lipstick 좀 짓궂은 장난들 I like it I'm twenty five날 좋아하는 거 알아I got this I'm truly fine이제 조금 알 것 같아 날긴 머리보다 반듯이 자른 단발이 좋아하긴 그래도 좋은 날 부를 땐 참 예뻤더라오 왜 그럴까 조금 촌스러운 걸 좋아해그림보다 빼곡히 채운 Palette 일기 잠들었던 시간들I like it I'm twenty five날 미워하는 거 알아I got this I'm truly fine이제 조금 알 것 같아 날어려서 모든 게 어려워 잔소리에 매 서러워꾸중만 듣던 철부지 애겨우 스무고개 넘어 기쁨도 잠시 어머아프니까 웬 청춘이래지은아 오빠는 말이야 지금 막 서른인데나는 절대로 아니야 근데 막 어른이 돼아직도 한참 멀었는데 너보다 다섯 살 밖에 안 먹었는데스물 위 서른 아래 고맘때 Right there애도 어른도 아닌 나이 때 그저 나일 때가장 찬란하게 빛이 나 어둠이 드리워질 때도 겁내지 마너무 아름다워서 꽃잎 활짝 펴서언제나 사랑 받는 아이 YOUPalette 일기 잠들었던 시간들I like it I'm twenty five날 좋아하는 거 알아I got this I'm truly fine이제 조금 알 것 같아 날아직 할 말이 많아I like it I'm twenty five날 미워하는 거 알아I got this I've truly found이제 조금 알 것 같아 날\n", 'song_id': '30378156', '작사': '아이유', '작곡': '아이유', '편곡': '이종훈'}
{'title': '가을 아침', 'artist': '아이유', 'lyrics': '\n이른 아침 작은 새들 노랫소리 들려오면 언제나 그랬듯 아쉽게 잠을 깬다 창문 하나 햇살 가득 눈부시게 비쳐오고 서늘한 냉기에 재채기할까 말까 음눈 비비며 빼꼼히 창밖을 내다보니 삼삼오오 아이들은 재잘대며 학교 가고 산책 갔다 오시는 아버지의 양손에는 효과를 알 수 없는 약수가 하나 가득 음딸각딸각 아침 짓는 어머니의 분주함과 엉금엉금 냉수 찾는 그 아들의 게으름이 상큼하고 깨끗한 아침의 향기와 구수하게 밥 뜸드는 냄새가 어우러진 가을 아침 내겐 정말 커다란 기쁨이야 가을 아침 내겐 정말 커다란 행복이야 응석만 부렸던 내겐 파란 하늘 바라보며 커다란 숨을 쉬니 드높은 하늘처럼 내 마음 편해지네텅 빈 하늘 언제 왔나 고추잠자리 하나가잠 덜 깬 듯 엉성히 돌기만 비잉비잉 음토닥토닥 빨래하는 어머니의 분주함과동기동기 기타 치는 그 아들의 한가함이심심하면 쳐대는 괘종시계 종소리와시끄러운 조카들의 울음소리 어우러진가을 아침 내겐 정말 커다란 기쁨이야가을 아침 내겐 정말 커다란 행복이야응석만 부렸던 내겐가을 아침 내겐 정말 커다란 기쁨이야가을 아침 내겐 정말 커다란 행복이야뜬구름 쫓았던 내겐이른 아침 작은 새들 노랫소리 들려오면언제나 그랬듯 아쉽게 잠을 깬다창문 하나 햇살 가득 눈부시게 비쳐오고서늘한 냉기에 재채기할까 말까 음\n', 'song_id': '30636089', '작사': '이병우', '작곡': '이병우', '편곡': '정성하'}
{'title': '사랑하지 않은 것처럼', 'artist': '버즈', 'lyrics': '\n늘 그랬었어 넌 참 예뻤어말할 때마다 웃는 눈도내가 아니어도 누군가사랑해 줄 사람 많을 거야아프지 않아 괜찮을 거야잊어줄게 보내줄게다신 널 찾지 않아안녕 내 사랑 돌아 보지마너 떠나도 나 울지 않을게부족했던 내가 더 많이 미안해이렇게 사랑이 끝나간다너의 번호를 지워 버렸어주고받았던 얘기들도내가 아니어도 누군가사랑해 줄 사람 많을 거야아프지 않아 괜찮을 거야잊어줄게 보내줄게다신 널 찾지 않을게안녕 내 사랑 돌아 보지마너 떠나도 나 울지 않을게부족했던 내가 더 많이 미안해이렇게 사랑이 끝나간다널 향한 내 사랑은 여기까진가 봐그 사람 곁에서 행복하길 바래잘 가너 떠나도 나 울지 않을게부족했던 나를 미워해도 좋아이렇게 사랑이사랑이 끝나간다\n', 'song_id': '30550293', '작사': '윤우현', '작곡': '윤우현', '편곡': '버즈'}
{'title': '바보에게 바보가', 'artist': '지아', 'lyrics': '\n너무 걱정하지는 마 보란 듯이 살아볼 거야후회는 사치일 뿐이야 다시 시작해볼게나 어제 또 울었어 나 어제 또 슬펐어왜 이런 바보를 사랑한 거니니 마음이 예뻐서 니 사랑이 고마워이젠 니 손을 잡고 다시 태어날 거야바보도 사랑합니다보내주신 이 사람 이제 다시는 울지 않을 겁니다나 이제 목숨을 걸고 세상 아픔에서 지켜줄게요이 사람을 사랑합니다널 위한다는 그 이유로 너를 보낼 뻔했어나 그렇게 바보야 넌 내 사랑 바보고서로를 많이도 울게 했었지니 사랑이 없다면 널 만날 수 없다면아마 나는 평생을 후회하며 살 거야바보도 사랑합니다보내주신 이 사람 이제 다시는 울지 않을 겁니다나 이제 목숨을 걸고 세상 아픔에서 지켜줄게요이 사람을그대가 울 때면 내 가슴은 무너져요무슨 남자의 눈물이 나처럼 서러워노력해 볼게 널 위해 살아갈게나약한 마음 따윈 모두 버릴게우리의 사랑을 위해 너의 손을 잡고 놓지 않을게사랑하는 내 사랑 바보야\n', 'song_id': '30777979', '작사': '정재하', '작곡': 'Minuki', '편곡': 'Minuki'}
{'title': '남이 될 수 있을까', 'artist': '볼빨간사춘기', 'lyrics': '\n쉴 새 없이 울려 대던 내 전화기는 잠잠해져 가할 말을 잃은 것 같아정신없이 쏟아내던 그 모진 말들 주워 담지는 못해아마 날 떠날 것 같아난 너를 지울 수 있을까그저 한 순간에 우린 남이 될 수 있을까쉽지 않을 걸 알지만 좋았던 날도 많았지만되돌리기엔 멀리 와 버린 걸까난 너를 지울 수 있을까우린 남이 될 수 있을까눈물조차 흐르지 않아 홧김에 던져 망가진 내 폰마치 날 보는 것 같아예전과 달리 잦아진 끝이 없는 듯한 감정싸움에이제 난 지친 것 같아난 너를 지울 수 있을까그저 한 순간에 우린 남이 될 수 있을까쉽지 않을 걸 알지만 좋았던 날도 많았겠지만되돌리기엔 멀리 와 버린 걸까괜찮은 척해도 먹먹해진 기분은진해져만 가 떨쳐내려 괜히 웃어보아도숨길 수 없는 걸 이별이 오는 걸우리의 시간은 멈춰버린걸난 너를 지울 수 있을까우린 남이 될 수 있을까난 너를 지울 수 있을까그저 한 순간에 우린 남이 될 수 있을까쉽지 않을 걸 알지만 좋았던 날도 많았지만되돌리기엔 멀리 와 버린 걸까난 너를 지울 수 있을까우린 남이 될 수 있을까We loved We loved We lovedWe loved We loved We loved\n', 'song_id': '30468654', '작사': '바닐라맨 (바닐라어쿠스틱)', '작곡': '바닐라맨 (바닐라어쿠스틱)', '편곡': '바닐라맨 (바닐라어쿠스틱)'}
{'title': 'Santa Tell Me', 'artist': 'Ariana Grande', 'lyrics': "\nSanta tell me if you're really thereDon't make me fall in love againIf he won't be here next yearSanta tell me if he really caresCause I can't give it all awayif he won't be here next yearFeeling Christmas all aroundAnd I'm trying to play it coolBut it's hard to focuswhen I see himwalking 'cross the roomLet it snow is blasting nowBut I won't get it in the moodI'm avoiding every mistletoeuntil I know it's true loveThat he thinks ofSo next ChristmasI'm not all alone boySanta tell me if you're really thereDon't make me fall in love againIf he won't be here next yearSanta tell me if he really caresCause I can't give it all awayif he won't be here next yearI've been down this road beforeFell in love on Christmas nightBut I knew you say I woke upand you wasn't by my sideNow I need someone to holdBe my fire in the coldBut it's hard to tell if this isjust a fling or if it's true loveThat he thinks ofSo next ChristmasI'm not all alone boySanta tell me if you're really thereDon't make me fall in love againIf he won't be here next yearSanta tell me if he really caresCause I can't give it all awayif he won't be here next yearOh I wanna have himbeside me like oohOn the 25th by the fireplace oohBut I don't want no broken heartThis year I got to be smartOh babySanta tell meSanta tell meSanta tell meSanta tell me if you're really thereDon't make me fall in love againIf he won't be here next yearSanta tell me if he really caresCause I can't give it all awayif he won't be here next yearSanta tell me if you're really thereDon't make me fall in love againIf he won't be here next yearSanta tell me if he really caresCause I can't give it all awayif he won't be here next year\n", 'song_id': '5475060'}
{'title': '떠나지마요', 'artist': '블락비 (Block B)', 'lyrics': '\n어딘지 숨어버린 설렘이 무뎌진 감정들이 돌이켜보니 또 착각이네 또 이래 과분하게 느껴진 너의 표현들이 이젠 그리워지려고만 해 너의 손을 잡고 눈 맞추면 눈 녹듯이 사라지던 내가 과연 널 내가 과연 너를 지울 수 있을까 있을까 난 그럴 자신 없는데 너의 말 가볍게 생각하며 스쳐 지나가던 나 한 번이라도 잠깐 자리에 서서 되짚어볼걸 너의 말 그 한마디 마디마저도 난 널 외면하고 난 또 상처를 주고 아무렇지 않은 듯 착각을 해요 떠나지마요 eh oh oh 떠나지마요 eh oh oh 떠나지마요 나 같은 놈 너 같은 여자는 못 찾아 떠나지마요 eh oh oh 떠나지마요 eh oh oh 떠나지마요 나 같은 놈 널 가진 건 과분했었나 봐 시간은 몸을 내던져도 날 무참히 밟고 가 이제 보기 좋게 무너지면 끝인 건가 정리할수록 오히려 속이 더 답답해져서 내뿜는 한숨에 네 이름이 들려와 서둘러 눈물 흘려도 이별이 너무 느려 내가 없는 네 행복을 바라는 게 많이 슬퍼 텅 빈 안부를 들추며 의미를 찾지만 기회가 나를 앞질러 간 뒤야 널 꽉 끌어안고 속삭이던 시간들이 떠오를 때 내가 과연 널 내가 과연 너를 지울 수 있을까 있을까 난 그럴 자신 없는데 너의 말 가볍게 생각하며 스쳐 지나가던 나 한 번이라도 잠깐 자리에 서서 되짚어볼걸 너의 말 그 한마디 마디마저도 난 널 외면하고 난 또 상처를 주고 아무렇지 않은 듯 착각을 해요 떠나지마요 eh oh oh 떠나지마요 eh oh oh 떠나지마요 나 같은 놈 너 같은 여자는 못 찾아 떠나지마요 eh oh oh 떠나지마요 eh oh oh 떠나지마요 나 같은 놈 널 가진 건 과분했었나 봐 Whatever you want I can handle it 그대를 사랑하는 내 맘 전하면 거의 미칠 것 같아서 더 미칠 것 같죠 아름답던 과거의 우릴 기억하기엔 지금의 내가 힘이 들어요 그때 우릴 반복하진 않을 테니 떠나지마요 \n', 'song_id': '30824538', '작사': '지코 (ZICO)', '작곡': '13', '편곡': '13'}
{'title': '빈차 (Feat. 오혁)', 'artist': '에픽하이 (EPIK HIGH)', 'lyrics': '\n갈 길이 먼데빈차가 없네.비가 올 것 같은데.처진 어깨엔 오늘의 무게.잠시 내려놓고 싶어.Home is far away.달라진 게 없네.홀로 남은 놀이터에서그 높은 턱걸이에 오른 뒤.여태 까치발 인생.내게 요구되는 건늘 높게 뻗은 두 손보다 조금 위.세상의 눈높이, 갈수록 에버레스트.정상을 향할수록 산더미만 되는 스트레스.I know I can never rest.내가 가진 불만들을 잠재워 줄수면제는 없으니 혀를 물고 밤 새워.어릴 적,줄 서는 것부터 가르쳐 준 이유 이젠 선명해졌어.복잡한 인간관계, 그 자체가 역설.관계만 있고 인간이 낄 틈 하나 없어.평범해지는 게 두려워서 꾸던 꿈.이젠 평범한 게 부럽군.As I stand all alone in the rain.자라지 않으면 성장통도 그저 pain.갈 길이 먼데빈차가 없네.비가 올 것 같은데.처진 어깨엔 오늘의 무게.잠시 내려놓고 싶어.Home is far away.갈수록 두려워.뛰고 있지만 뭘 위해서였는지 잊은 두 발과 심장.그저 짐이 되어버린 꿈.두고 달리는 게 내게 유일한 희망.한 걸음만 더 떼라 부추기네.고개 들었더니 앞은 낭떠러진데.뒤를 보니 길게 줄 선 많은 기대가날 지탱하는 척하며 등을 떠미네.언젠가 찍고 싶었던 마음의 쉼표가숫자들 사이 뒤엉킨 이상.계산적인 이 세상이 들이미는 손잡기 싫지만, 빈손 되는 게 더 겁이 나.붙잡아도 갈 길 가는 게 시간 뿐이겠어?먹구름 낀 하늘을 보며,한때 나도 꿈이라는 게 있었는데오늘 밤은 잠들기도 어렵네.날 위해 잠시멈춰주면 안 될까요?더는 걷기가 힘든데.바람이 불고 아직도갈 길이 먼데빈차가 없네.비가 올 것 같은데.처진 어깨엔 오늘의 무게.잠시 내려놓고 싶어.Home is far away.이 넓은 세상에 내 자린 없나?붐비는 거리에 나 혼자인가?날 위한 빈자리가 하나 없나?Home is so far away.내가 해야 할 일,벌어야 할 돈 말고도 뭐가 있었는데.내가 해야 할 일,벌어야 할 돈 말고도 뭐가 있었는데.내가 해야 할 일,벌어야 할 돈 말고도 뭐가 있었는데.내가 가야 할 길,나에게도 꿈같은 게 뭐가 있었는데.\n', 'song_id': '30688502', '작사': '미쓰라 진', '작곡': 'Tablo', '편곡': 'DJ 투컷츠'}
{'title': 'You', 'artist': '멜로망스', 'lyrics': '\n어떻게 난 해야 해 니가 떠난다고 말하면 난 혼자 남겨지는 게 더 두려울 텐데 이유를 말해준다면 조금 편할 것 같아 아주 작은 손짓조차도 내겐 소중한 너를 잊을 수 없는 슬픈 기억 속으로 보내 잠 못 이루겠지YOU 비가 오는 거리에 혼자 버려진 채로 서 있는 날 생각해 봤니 혼자 있는 밤이면 니가 잠이 들던 자리엔 슬피 우는 나의 눈물로 모두 젖어 들 거야모두가 말했었어 둘이 잘 어울린다고 그럴 땐 넌 내 품에 기대어왔어 이젠 눈을 감으면 꿈속에서 널 만나 긴 밤을 지내다 널 아침이 되면 난 잠에서 깨어 다시 보내고 난 후 아파 눈물 흘리겠지 YOU 비가 오는 거리에 혼자 버려진 채로 서 있는 널 생각해 봤니 혼자 있는 밤이면 니가 잠이 들던 자리에 슬피 우는 나의 눈물로 모두 젖어 들 거야 YOU 비가 오는 거리에 혼자 버려진 채로 서 있는 널 생각해봤니 혼자 있는 밤이면 니가 잠이 들던 자리에 슬피 우는 나의 눈물로 모두 젖어 들 거야 \n', 'song_id': '30849733', '작사': '신영웅', '작곡': '신영웅', '편곡': '정동환'}
{'title': 'Twilight', 'artist': 'Wanna One (워너원)', 'lyrics': '\n뒤돌아 서기가 너무 힘들어바래다 줄 때마다 보내기 싫어서오늘따라 더 눈이 부시네Sunshine Sunshine아니 너 말이야Moonlight Moonlight보다 훨씬 빛나 넌I’m missing you I’m missing you바로 옆에 있는데도I’ll be with you I’ll be with you너라는 이유Fall in love GirlStay 지금 이대로멈춰진 시간 속에 NowStay 지금 이대로언제까지나 머물러줘Twilight Twilight Twilight TwilightTwilight Twilight Twilight TwilightTwilight Twilight Twilight TwilightWant you to stay머물러줘Beautiful Wonderful식상한 얘기내 기분 그 정도론 표현 할 수는 없어Ay 네 앞에선 Stupid자꾸 했던 농담 또 해근데 웃어주네너도 내 마음과 같은 걸까너 때문에 그래도 웃어불안한 미래도 잊어 다 잊어욕심일까 내게 넌I’m missing youI’m missing youI’m missing youI’m missing you바로 옆에 있는데도I’ll be with you YouI’ll be with you You너라는 이유 BabyFall in love GirlStay 지금 이대로멈춰진 시간 속에 NowStay 지금 이대로언제까지나 머물러줘고백 하고 싶은데돌아서야 하는 가봐아무것도 지금 해줄 수 없어서Fall in love GirlStay 지금 이대로멈춰진 시간 속에 NowStay 지금 이대로언제까지나 머물러줘Twilight Twilight Twilight TwilightTwilight Twilight Twilight TwilightTwilight Twilight Twilight TwilightWant you to stay머물러줘\n', 'song_id': '30725484', '작사': '미친손가락', '작곡': '미친손가락', '편곡': '미친손가락'}
result-size: 100
    '''